### ISSUE TITLE
Search Needs to go to dossier

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#1]
Search returns user to Map page, rather than taking them to a dossier or map with mini-dossier as expected

Example:
- From home page, choose Nigeria.
- Select “ Search"
- Select “Persons"
- Search "Dahiru Bako”
- Four results are returned, choose any of them
- The overlay is removed and the user is returned to the map screen.
- Expected behavior is that it would take the user to the Person dossier, showing that Person in the command hierarchy

**Comment by sam-ffctn** [comment]
It will now show the mini-dossier of the selected item.

**Comment by tonysecurityforcemonitor** [comment]
Great thanks!
