### ISSUE TITLE
Chart - Shuffling around selected organization/person

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#10]
When an Organization is selected in the Chart - it's Parent/superior Organization is often several screens to the right or left - making it impossible for the user to be able to read the chart

This seems to be a result of the Chart being a static image -- a solution could be that the Chart "shuffles" or otherwise rearranges itself around the Organization selected - so that the parent/superior organization is always directly above it

There may be other ways to solve this issue - I'm open to other fixes

**Comment by sam-ffctn** [comment]
We reduced the size of the nodes (padding and width). This makes the chart a lot more vertical. We may tweak the style further to increase readability. 
http://ffctn.com/clients/on/sfm/M13/#country/ng/o/741b1748-f740-4dd5-b6cc-107405bf0e96!date=2014-01-01&focus=chart

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn This is tied to #21 - so its a little hard to test right now
