### ISSUE TITLE
Chart - Zooming

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#12]
Zoom does not seem to work with mouse button - and there is no "+" or "-" buttons either

**Comment by sam-ffctn** [comment]
Zoom now works with double click, scroll wheel, and by clicking on the "+" and "-" buttons.
http://ffctn.com/clients/on/sfm/M13/#country/ng/o/147eb0bc-3516-4d3f-a5cb-fd9a396ed8ec!date=2014-01-01&focus=map&overlay=

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor added +/- buttons, added zoom on scroll wheel.

http://ffctn.com/clients/on/sfm/M15/#country/ng/o/eba73af9-f22a-425f-832d-c8a36b7e5e50!date=2014-01-01&focus=chart
