### ISSUE TITLE
Map - Mini Dossier - Sources Need Numbering

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#13]
In the Mini Dossier on the side of the Map function the various citations are numbered but when the user scroll to the bottom to Sources they are listed but not numbered 

(example screenshot at top of mini dossier)

![image](https://cloud.githubusercontent.com/assets/18744855/19320721/7267f8e8-9080-11e6-9d0a-6b996990981a.png)

(example screenshot at bottom of same mini dossier)

![image](https://cloud.githubusercontent.com/assets/18744855/19320758/8ec4511c-9080-11e6-9cd7-e9e72ead8af0.png)

**Comment by sam-ffctn** [comment]
They are now numbered and clickable (when a url is present)
ex:
http://ffctn.com/clients/on/sfm/M13/#country/ng/o/147eb0bc-3516-4d3f-a5cb-fd9a396ed8ec!date=2014-01-01&focus=map&overlay=organization-dossier

**Comment by tonysecurityforcemonitor** [comment]
Ok great I see that's working now.
