### ISSUE TITLE
Change display for Confidence Scores

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#14]
The current Red, Yellow and Green Diamonds to indicate confidence score aren't working as well as I hoped. We should change them to text displays, similar to how they were envisioned in older versions of the mockups:

![image](https://cloud.githubusercontent.com/assets/18744855/19445325/cca5d5e8-9461-11e6-8fbd-37cbe7ef52a6.png)

**Comment by sam-ffctn** [comment]
We reverted it back to text, but preserved the colors.
ex:
http://ffctn.com/clients/on/sfm/M13/#country/ng/o/147eb0bc-3516-4d3f-a5cb-fd9a396ed8ec!date=2014-01-01&focus=map&overlay=organization-dossier

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn - Great I think these work well
