### ISSUE TITLE
Organization Classification not displaying/loading properly

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#15]
@evz @sam-ffctn I'm not sure if this is an API or UI issue...

1. Currently Organizations all seem to have the classification of Unknown. As far as I can see in the CMS every organization has at least one classification - so no organization should be listed with an Unknown classification.
2. The other classifications are merged together, rather than being counted as two (or more) separate classifications - example screenshot below:

![image](https://cloud.githubusercontent.com/assets/18744855/20976963/2630f4f2-bc72-11e6-88cd-974301395904.png)

It should be clear that this organization has multiple classifications - which I think would mean that it would like this:

![image](https://cloud.githubusercontent.com/assets/18744855/20977375/65ef7860-bc73-11e6-802e-418cb960031e.png)

**Comment by evz** [comment]
I think this was partially an API issue. There were `null` values being returned in those responses which should be gone now. I'll let @sam-ffctn confirm whether or not that is what was causing this display problem.

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn How is this issue looking?

**Comment by sam-ffctn** [comment]
This issue should now be fixed 
http://ffctn.com/clients/on/sfm/M14/#country/ng/o/e3d1062a-4346-4d83-a7e3-afa697bc3b5d!date=2014-01-01&focus=map
this was mostly a front-end bug.
