### ISSUE TITLE
Person Dossier - Mini Dossier/Full Dossier - Sources not displaying

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#17]
@sam-ffctn - The sources don't seem to be displaying on either the mini or full dossiers for people.

Example screenshot, mini-dossier:

![image](https://cloud.githubusercontent.com/assets/18744855/20979711/e01fd898-bc7b-11e6-9e1a-a401aab63fec.png)

Example screenshot, full dossier:

![image](https://cloud.githubusercontent.com/assets/18744855/20979748/fa751636-bc7b-11e6-9f7b-e2c04a4652f2.png)

**Comment by sam-ffctn** [comment]
Fixed the sources on person Dossier and mini dossier
http://ffctn.com/clients/on/sfm/M14/index.html#country/ng/p/705c584e-5316-4cf6-b13b-400453bf53df!date=2014-01-01&focus=map&overlay=person-dossier

On another note, I notices that quite a few fields have sources that we aren't displaying (title, rank and role all have a few sources each). Should we display the sources for all fields that have them?

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn @evz an API error is preventing me from testing this.

And @sam-ffctn yes we should absolutely display sources for all fields that have them - for People, Organizations and Events

**Comment by evz** [comment]
This seems to be related to what I mentioned over here: https://github.com/security-force-monitor/sfm-ui/issues/16#issuecomment-269529086

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn @evz This also appears to be resolved - sources displaying for multiple fields
