### ISSUE TITLE
Events - not loading sources

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#18]
@sam-ffctn - Events do not seem to have their sources displayed anywhere in the mini-dossier - screenshot example:

![image](https://cloud.githubusercontent.com/assets/18744855/21112118/7ee5be8a-c072-11e6-99c7-a7cb2c799b28.png)

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor I don't see any sources in the data. I'm not exactly sure what's supposed to have a source.

I'm making sure that the Alleged perpetrator organization/person is properly getting pulled from the data, but I'm not sure if that's what you where talking about.

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn The source should be a citation similar to citiations for People and Organizations. I checked that the sources are in the CMS - @evz is there an API issue here?

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @evz It seems like this might be an API issue. I still can't see any sources in the data. 
Sample request: https://sfm.datamade.us/api/events/aa69335b-4bb3-4c71-a31e-757046700323/
But then again in the API documentation I don't see any mention of sources either.

**Comment by evz** [comment]
@tonysecurityforcemonitor It sounds like we want sources for the event detail view? I can add that into the response.

**Comment by tonysecurityforcemonitor** [comment]
@evz Yes thanks!

**Comment by evz** [comment]
OK, the event detail response should include a list of sources for the event

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor the sources should now be listed for the events

http://ffctn.com/clients/on/sfm/M17/#country/ng/e/d4929e67-540b-4afd-be9e-7297e67e8a12!date=2014-01-01&focus=map

@evz 
A few issues with the API
1) The sources are nested in an additional array for no apparent reason, this seems like it might be a bug
2) Sometimes duplicate sources are listed.

I worked around the first issue, but I think its worth fixing if it's indeed a bug. 

sample event source property
```
[
   [
      {
         "published_on":"2009-12-09",
         "publication_id":"d74f95a7-bac6-4ad3-b32f-1f987db084d7",
         "accessed_on":null,
         "date_updated":"2016-12-14T17:52:27.596924+00:00",
         "title":"“Killing at Will: Extrajudicial Executions and Other Unlawful Killings by the Police in Nigeria",
         "id":2040,
         "page_number":null,
         "archive_url":null,
         "date_added":"2016-12-14T17:52:27.596944+00:00",
         "source_url":"https://www.amnesty.org/en/documents/afr44/038/2009/en/",
         "user_id":3
      }
   ],
   [
      {
         "published_on":"2009-12-09",
         "publication_id":"d74f95a7-bac6-4ad3-b32f-1f987db084d7",
         "accessed_on":null,
         "date_updated":"2016-12-14T17:52:27.596924+00:00",
         "title":"“Killing at Will: Extrajudicial Executions and Other Unlawful Killings by the Police in Nigeria",
         "id":2040,
         "page_number":null,
         "archive_url":null,
         "date_added":"2016-12-14T17:52:27.596944+00:00",
         "source_url":"https://www.amnesty.org/en/documents/afr44/038/2009/en/",
         "user_id":3
      }
   ]
]
```

**Comment by evz** [comment]
@sam-ffctn I have a fix for this and will deploy it today with other things that were raised last week.

**Comment by evz** [comment]
@sam-ffctn The fix for this should now be live on the API

**Comment by tonysecurityforcemonitor** [comment]
@evz I'm getting an API error that is preventing testing - I get it on http://ffctn.com/clients/on/sfm/M18/#country/ng!date=2014-01-01&focus=map

**Comment by evz** [comment]
@sam-ffctn It looks like a couple of the requests are timing out. Can you give me the URLs that you are trying to hit?

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn @evz Yes unfortunately the map http://ffctn.com/clients/on/sfm/M18/#country/ng!date=2014-01-01 is taking forever to load... its making it so I can't test anything.

**Comment by evz** [comment]
@tonysecurityforcemonitor I'm working on a couple server level things to make those queries run a little faster. I'll have that ready today and hopefully it'll mean we don't really need to change anything else.

**Comment by evz** [comment]
@tonysecurityforcemonitor @sam-ffctn I just got everything setup on the new server so you should notice a pretty decent performance boost. I added some server side caching, too so, once a resource is fetched and cached, it'll be very fast to load the next time.

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn @evz I see the sources are loading now in the Event dossier - and the performance is much better too! I think this resolves everything but there was some API and other discussion so let me know if this issue is ok to close.

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor The API issue is resolved, I think we can close this issue.
