### ISSUE TITLE
Events - Site Name loading from Site ID

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#19]
Hey @sam-ffctn @evz - not sure where the issue lies, but the instead of the Event:geonames_name it's loading the Event:geonames_id. The Event:admin_level_1_geonames_name is displaying fine however. (I know we've switched over to OSM, but I wasn't sure how those classes were renamed so I kept them the same as they are in the Classes Sheet).

 Example screenshot below:

![image](https://cloud.githubusercontent.com/assets/18744855/21112277/3cf368e6-c073-11e6-9e6f-1c3847608e01.png)

**Comment by sam-ffctn** [comment]
It would be good to know what properties I should be using from the `events/:id` endpoint. 
ex: https://sfm.datamade.us/api/events/f77be141-772a-4dca-9846-c9f4183a8b07/

I was using the `admin_level_1` and `admin_level_2` but now I switching to using `location_description`, I'm not exactly sure if this is equivalent to `geonames_name`

url with update: http://ffctn.com/clients/on/sfm/M14/#country/ng/e/f77be141-772a-4dca-9846-c9f4183a8b07!date=2014-01-01&focus=map

**Comment by tonysecurityforcemonitor** [comment]
@evz @sam-ffctn - this seems like this might be an API issue... I don't think that the admin_level_1 should be returning a number string

**Comment by evz** [comment]
I worked on this a bit and found that I was just getting the info for the admin level 1 field from the wrong column in the spreadsheet. The upshot is that I had to re-import all the events which made new IDs for them so the links above are now broken (because an event with that ID doesn't exist anymore)

**Comment by sam-ffctn** [comment]
I switched back to using `admin_level_1` and `admin_level_2`. Seems to be working fine. Although a lot of the events have `null` for `admin_level_1`

http://ffctn.com/clients/on/sfm/M15/#country/ng/e/92593738-81f2-495d-9726-3aa6b83850ff!date=2014-01-01&focus=map

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn great - many events have null for admin_level_1 simply because the source for the event itself doesn't have an admin_level_1
