### ISSUE TITLE
Map - Zoom needs to be clear

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#2]
Having "+" and "-" buttons would be helpful

**Comment by sam-ffctn** [comment]
Zoom now works with double click, scroll wheel, and by clicking on the "+" and "-" buttons.
http://ffctn.com/clients/on/sfm/M13/#country/ng/o/147eb0bc-3516-4d3f-a5cb-fd9a396ed8ec!date=2014-01-01&focus=map&overlay=

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn - Thanks this works well.
