### ISSUE TITLE
Events - Event:classification not displaying

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#20]
@sam-ffctn

**Comment by sam-ffctn** [comment]
Added the Classification field to the event
http://ffctn.com/clients/on/sfm/M14/#country/ng/e/f77be141-772a-4dca-9846-c9f4183a8b07!date=2014-01-01&focus=map

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn The classification isn't displaying in the tooltip on the map - example screenshot:

![image](https://cloud.githubusercontent.com/assets/18744855/21457554/483d79ec-c8fe-11e6-92bb-a1f00f8beec9.png)

**Comment by sam-ffctn** [comment]
I've added it to the tooltip
http://ffctn.com/clients/on/sfm/M14/#country/ng/e/3ba4c4d9-04c7-4a86-910c-c5a361c4c733!date=2014-01-01&focus=map

**Comment by tonysecurityforcemonitor** [comment]
Perfect - thanks
