### ISSUE TITLE
Chart - Doesn't Display Hierarchy

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#21]
@sam-ffctn - 

Steps:
1) A user selects an Organization from the drop down menu on the Map page
2) From the Organization's mini dossier they select Chart
3) On the Chart page the selected Organization is at the "top" of the hierarchy - with no way to see what the parent organizations are.

Example http://ffctn.com/clients/on/sfm/M13/#country/ng/o/03e9b83d-ddeb-491d-baaf-c09a49f1f64d!date=2014-01-01&focus=chart - and screen:

![image](https://cloud.githubusercontent.com/assets/18744855/21154573/dd9d1214-c13c-11e6-9a52-b27fa1315253.png)

Example http://ffctn.com/clients/on/sfm/M13/#country/ng/o/04bf35af-87de-4c13-a9c3-b727a08ce891!date=2014-01-01&focus=chart - and screen:

![image](https://cloud.githubusercontent.com/assets/18744855/21154492/890b2ab0-c13c-11e6-994e-61b9594c38d3.png)

**Comment by sam-ffctn** [comment]
We now render the parent of the selected organization
http://ffctn.com/clients/on/sfm/M15/#country/ng/o/9f942b60-1e10-4e0a-a859-04f42dcc4df6!date=2014-01-01&focus=chart&perspective=organizations

**Comment by tonysecurityforcemonitor** [comment]
@evz @sam-ffctn 

This doesn't seem to be working as expected yet - the Commander is not populating in the Chart - also the date displayed isn't matching up with what is selected in the timeline - screenshot example:

![image](https://cloud.githubusercontent.com/assets/18744855/21573473/c0547156-ceb2-11e6-931b-5324b16f8b73.png)

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor fixed issue with the commander not rendering properly, fixed the date offset.

http://ffctn.com/clients/on/sfm/M16/#country/ng/o/9f942b60-1e10-4e0a-a859-04f42dcc4df6!date=2013-01-01&focus=chart

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn while testing this I got an error -

1. followed link from your post above
2. Clicked through timeline to test and it worked
3. Clicked on Ugwu Chima on the mini-dossier

The Person mini dossier failed to load - instead the left column was simply blank.

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor I think this issue was just the API being slow at responding. I added a spinner to help make it clearer when things are loading and not broken. I will also be looking at caching responses which should decrease loading times/ strain on the server.

http://ffctn.com/clients/on/sfm/M16/#country/ng!date=2014-01-01

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor  @evz I added the client side cache now, so it should make things at least a little faster and I added some reasonable tolerances. I'm not sure I can make it any faster on the client side after this. 

I think the issue above is resolved tho.

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn Yep everything is working now - except for the issues mentioned in #11 - I like the spinner functionality its nice to let the user know things are loading.
