### ISSUE TITLE
Map - Can't use Organization's Classification to filter

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#22]
The Filter functionality doesn't load any classifications from the Organizations. I would expect to be able to use the Filter function to select only to display Organizations with the classification of Police or Army or Military.

**Comment by sam-ffctn** [comment]
What filter function are we talking about? The filter functionality built into the legend?

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn I'm referring to the Filter button which is right below the Organizations label and above the list of organizations - example screen shot:

![image](https://cloud.githubusercontent.com/assets/18744855/21462211/4ecd880a-c927-11e6-952b-88ccb3c35753.png)

**Comment by sam-ffctn** [comment]
@evz @tonysecurityforcemonitor to do this I would need the api endpiont https://sfm.datamade.us/api/countries/ng/map/?at=2014-01-01 to return the classifications for the organizations. Would it be possible to add this property? I've addressed this issue already in a previous email:

> /organizations/:id/map currently doesn't have classifications defined for each organization.
This endpoint is used to fill the organization list which shows the classification so it would be really useful to include.

**Comment by evz** [comment]
I added the classifications to the `/organizations/:id/map/` response yesterday. I'll take a look at the `/countries/:id/map/` endpoint to see if it'll be difficult to incorporate there as well (I imagine it won't be).

**Comment by evz** [comment]
OK, the `/countries/:id/map/` response should include a list of classifications within the `properties` object within each organization now.

**Comment by sam-ffctn** [comment]
@evz sorry about that I meant to say `/countries/:id/map/` originally. Thanks for the quick fix :)

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor Added classifications to filter. Selecting them will reduce the list of organizations, which now also have their classifications listed.

http://ffctn.com/clients/on/sfm/M15/#country/ng!date=2014-01-01&focus=map

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn Great the filter is working on the organization list --- however the map doesn't change accordingly. The expected interaction is that the map would also only list organizations with the classification selected in filter.

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor The map now updates based on the classifications filter
http://ffctn.com/clients/on/sfm/M15/#country/ng!date=2014-01-01&focus=map&classifications=Military

**Comment by tonysecurityforcemonitor** [comment]
Works well - thanks!
