### ISSUE TITLE
Error message?

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#23]
There is some latin text at the top of the page - I'm not sure what's triggering it.

![image](https://cloud.githubusercontent.com/assets/18744855/21573289/c1cb9a20-ceb0-11e6-9f28-9c8d28733c8c.png)

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor I'm not able to reproduce this issue. Could you provide the steps to reproduce it? 

It seems like this is content from the about page. Does the about page still look as expected? 

This also reminds me that we need content for the about page. Would it be possible to provide it?

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn - I get it for every page I'm on --- for instance going to the link you posted in another issue triggered the text: http://ffctn.com/clients/on/sfm/M16/#country/ng/o/9138b29e-c66a-4431-ba24-161d9e44a44c!date=2014-01-01&focus=map

We can scrap the about page as we are currently planning to have the relevant information on the main website of the Monitor project rather than within the application.

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor  I removed the about page, let me know if this solves the problem.

http://ffctn.com/clients/on/sfm/M16/#country/ng/o/9138b29e-c66a-4431-ba24-161d9e44a44c!date=2014-01-01&focus=map

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn Yep all set on this one
