### ISSUE TITLE
Dossiers - Founding Date/First Citation Date and Dissolution/Last Citation Date

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#24]
@sam-ffctn - Can we get rid of these two sections of the mini/full dossiers? There was a complicated plan around this - but we are capturing the same data with the Sites of each organization.

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor I removed these fields from the Organization mini/full dossier as well as from the Organization search page. 
I also notices it was a field on the Persons search page and I removed it there to.
Let me know if this is what you wanted.

http://ffctn.com/clients/on/sfm/M16/#country/ng/o/9138b29e-c66a-4431-ba24-161d9e44a44c!date=2014-01-01&focus=map

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn  Looks good!
