### ISSUE TITLE
Back button not working?

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#25]
Just noticed this right now - its across the Map and Chart functionalities

![image](https://cloud.githubusercontent.com/assets/18744855/21573584/375eddc6-ceb4-11e6-931a-a45f444b55f5.png)

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor The back button seems to be working as intended. Right now the functionality is as follows:
*Current Section -> Section after pressing back*
Country description -> Country List
Organizations list -> Country description
Organization -> Organization list
Person -> Organization list
Event -> Organization list
Chart Page -> Map Page

let me know if this should behave differently or you aren't getting these results.

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn - currently I am getting no response whatever from clicking on the button. I think it might be related to #23 in some way....

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor I removed the about page, let me know if this solves the problem.

http://ffctn.com/clients/on/sfm/M16/#country/ng/o/9138b29e-c66a-4431-ba24-161d9e44a44c!date=2014-01-01&focus=map

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn yep back is working now
