### ISSUE TITLE
Mini/Full Dossier - Headquarters not reading correct data?

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#26]
@sam-ffctn - The Headquarters appears to be reading the administrative_level_1 but not the administrative_level_2

http://ffctn.com/clients/on/sfm/M16/#country/ng/o/1596e4f4-85a4-47a5-8bef-39f2e72cc98f!date=2014-01-01&focus=map&overlay=organization-dossier

Relatedly - the Current Location map doesn't seem to be reading any data (I would expect to show the headquarters location surronded by the area of operations)

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @evz 

The only properties I have for sites (headquarters) are:
```
admin_level_1_osm_name: null
date_first_cited: "2007-10-09"
date_last_cited: "2015-01-18"
id: 20
name: "Mubi"
osm_name: "Mubi"
```

and for areas of operation I have:
```
first_cited: "2013-09-15"
id: "87ac8025-de2e-4292-971d-535d3d53e93e"
last_cited: "2015-01-11"
name: "Adamawa"
osm_name: "Adamawa"
osmid: 3720358
```

I'm not sure I have the data for the administrative_level_2 property. 

I understand that the area of operations wasn't showing at all as well as for the current location(mini map). I'm working on a fix for that now. For now as a fallback I'm just showing the "name" for both the area and site until we get the level_2 stuff.

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn @evz 

Ok - this looks like a bit of mix of API and UI issues. 

As I understand it the Site/Headquarters listing in the UI in the dossiers should have the following componants:

Site:Name (Column Y in the Master Import Sheet) 
Site	admin_level_1_geonames_name (Column AB)
Site	admin_level_2_geonames_name (Column AF)
date_first_cited (Column AK)
date_last_cited (Column AO)

So the 3 Armoured Division (http://ffctn.com/clients/on/sfm/M17/#country/ng/o/765f0a38-22d3-4115-86b3-0c03d829ae02!date=2014-01-01&focus=map&classifications=Army&overlay=organization-dossier) should have a Site/Headquarters of:

Rukuba Barracks, Jos, Plateau 1967-12-30 - 2016-06-17

Currently the UI seems to be displaying this slightly differently in the Mini Dossier (http://ffctn.com/clients/on/sfm/M17/#country/ng/o/765f0a38-22d3-4115-86b3-0c03d829ae02!date=2014-01-01&focus=map&classifications=Army)

![image](https://cloud.githubusercontent.com/assets/18744855/21944438/3b3e6556-d9a4-11e6-985f-6f15bdd00756.png)

And in the full Dossier (http://ffctn.com/clients/on/sfm/M17/#country/ng/o/765f0a38-22d3-4115-86b3-0c03d829ae02!date=2014-01-01&focus=map&classifications=Army&overlay=organization-dossier)

![image](https://cloud.githubusercontent.com/assets/18744855/21944466/530bdd26-d9a4-11e6-85e0-7d98b3c8a88e.png)


The main difference seems to be displaying N/A for values that the UI doesn't have. Since some Organizations don't have Site:Name or even a Site:admin_level_1_geonames_name - it would be best if the UI worked like the full dossier and didn't displaying any N/A for missing data (as I think an N/A would be confusing to the user in this context)

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @evz 

Right now the API doesn't seem to be returning `admin_level_1_geonames_name` or `admin_level_2_geonames_name`.

 I'll wait until the API is updated before solving these issues. Should be a quick fix once we have that.

As a side note, the location map should be fixed now on the latest version.

**Comment by evz** [comment]
@tonysecurityforcemonitor Oh, ha. I see what's going on. I am getting the Site:Name from the wrong column. Fix incoming.

**Comment by evz** [comment]
@sam-ffctn @tonysecurityforcemonitor The Site names should be worked out now

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn @evz There still seems to be an issue with this loading data - for instance: http://ffctn.com/clients/on/sfm/M18/#country/ng/o/9067a45a-be22-4a89-8010-835d0586c3e7!date=2014-01-01&focus=map&overlay=organization-dossier

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @evz the Headquaters name is now pulled from the `osm_name` property for both the dossier and mini dossier.
ex: http://ffctn.com/clients/on/sfm/M19/#country/ng/o/9067a45a-be22-4a89-8010-835d0586c3e7!date=2014-01-01&focus=map&overlay=

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn @evz - There is still a small issue with this - it might be a CMS/API issue... I'd expect the Headquarters for this unit to be Makurdi, Benue - or Site OSM Name (column AB in Master Import), Admin 1 OSM Name (column AF in Master Import). Looking at the entry for this unit in the CMS it appears that Site OSM Name and Admin 1 OSM Name are both Makurdi which might be the root of the issue.

**Comment by evz** [comment]
Oh, OK, so, the headquarters should be (Site OSM Name) + (Admin 1 OSM Name) if it's not specified as something else?

**Comment by tonysecurityforcemonitor** [comment]
@evz - sorry I forgot one thing - headquarters should be Headquarters (Barracks, Base, Physical Asset) + (Site OSM Name) + (Admin 1 OSM Name). Most entries will only have data for (Site OSM Name) + (Admin 1 OSM Name) - and some will only have data for (Admin 1 OSM Name). Everything should have an (Admin 1 OSM Name) --- if it doesn't I should fix in the data.

Can you share an example when it's specified as something else? In mind it's always some combo of these things.

**Comment by evz** [comment]
Oh that's what I was talking about. If the "headquarters" column was blank, I was leaving the site name blank. It makes sense for the site name to be a combination of those columns. I'll fix that.

**Comment by evz** [comment]
Oh, I guess I never followed up on this. I went through and concatenated the names in the way that @tonysecurityforcemonitor suggested.

**Comment by tonysecurityforcemonitor** [comment]
@evz @sam-ffctn - This still isn't working as expected... - examples:

**All fields related to Site/Headquarters should be in CMS**
http://ffctn.com/clients/on/sfm/M19/#country/ng/o/1d5b6310-68af-4402-a2a4-d61a2aae9236!date=2014-01-01&focus=map&overlay=organization-dossier

- Headquarters is listed as: Brinin Kebbi
- I'd expect: Dukku Barracks (confidence score, sources), Birnin Kebbi (confidence score, sources), Kebbi (confidence score, sources)

**Only has data for Site:admin_level_1_geonames_name**
http://ffctn.com/clients/on/sfm/M19/#country/ng/o/3aed3ec7-7f64-46d9-9ec8-6c099e2a8b31!date=2014-01-01&focus=map&overlay=organization-dossier

- Headquarters is listed as: (blank)
- I'd expect: Kaduna (confidence score, sources)

**Only has data for Site:geonames_name and Site:admin_level_1_geonames_name**
http://ffctn.com/clients/on/sfm/M19/#country/ng/o/b21e0f4c-d84b-4c33-ab9f-a9cc32622c77!date=2014-01-01&focus=map&overlay=organization-dossier

- Headquarters is listed as: Kaduna
- I'd expect: Kaduna (confidence score, sources), Kaduna (confidence score, sources)

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @evz the organizations seemed to have change ids and all the above links are broken (The API returns an empty object for GET /organizations/:id). 

I have however changed the displayed heaquarter (now called installations) to the `sites.properties.name` I was displaying `sites.properties.osm_name` previously.

I'm not exactly sure if this addresses this issue. 

example site:
from https://sfm.datamade.us/api/organizations/8571f8e4-a3f1-40d6-ad60-c155c247920e/
```
admin_level_1_osm_name: "Adamawa"
date_first_cited: "2014-11-22"
date_last_cited: "2015-01-14"
id: 35
name: "Yola, Adamawa"
osm_name: "Yola"
```

latest version: http://ffctn.com/clients/on/sfm/M20/

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn The changed ids is a result of the new import I believe --- regardless this is working exactly as I'd expect - thanks!
