### ISSUE TITLE
Mini/Full Dosser - Area of Operations not reading data?

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#27]
@sam-ffctn - related to #26 the Area of Operations is not being loaded - even though an area of operations is loaded on the Map

http://ffctn.com/clients/on/sfm/M16/#country/ng/o/1596e4f4-85a4-47a5-8bef-39f2e72cc98f!date=2014-01-01&focus=map&overlay=organization-dossier

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @evz 

The area of operation should be showing now, but I can only show what I get from the API, I still need the admin_level_1 and admin_level_2 fields before being able to complete this issue.

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn This does seem to be working well -- the Area of Operations should only have one area related to it (rather than admin_level_1 and admin_level_2 which would be related to a Site) - @evz do I have that right in terms of the API? I think we might actually be able to close this issue, but want to confirm first.

**Comment by evz** [comment]
@tonysecurityforcemonitor Yeah, that's right. We don't capture that info about an Area in the database. If we wanted to, we could infer it based upon the OSM ID but it's not in the API (nor is it in the database or Master Import spreadsheet for that matter).

**Comment by tonysecurityforcemonitor** [comment]
@evz - wait - but that's what Columns AS through BD are capturing

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @evz I'm not sure if any changes still need to be made on the front-end as far as I know the correct values are being displayed.

**Comment by tonysecurityforcemonitor** [comment]
@evz @sam-ffctn - I'm trying to check this using Zone 7 Police Command http://ffctn.com/clients/on/sfm/M19/#country/ng/o/0d381563-5575-4542-97d7-830224d0bb3c!date=2014-01-01&focus=map&overlay=organization-dossier

In the CMS this organization has more than one AOO (Niger, Kaduna and Federal Capital Territory) but in the UI only Niger is being displayed on the map and it is the only one displayed in the dossier as well. Figuring out this will also impact #7

**Comment by evz** [comment]
@tonysecurityforcemonitor I'll take a look into this. It looks like the API is only returning the one area.

**Comment by evz** [comment]
@tonysecurityforcemonitor OK, that should be fixed now. Looks like the UI is displaying all three, as well.

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn - The only issue left on this is with the tooltip for Zone 7 which only lists Niger as an Area of Operation. The dossier lists the correct three entries however.

**Comment by tonysecurityforcemonitor** [comment]
will create new issue for the tooltip issue
