### ISSUE TITLE
Mini/Full Dossier - Adding Dates for Commanders?

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#28]
@sam-ffctn - could we add the dates for current and former commanders on an Organization's Mini and/or Full Dossier? It would be really helpful for users to get a quick sense of who served when

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor the dates have been added. (both mini and full dossier)

http://ffctn.com/clients/on/sfm/M17/#country/ng/o/a91af551-a806-426b-832a-01a5cf6f2456!date=2014-01-01&focus=map

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn This looks great! Can we rank the former commanders by date of first citation so that it flows in chronological order?

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor ok they are now ordered in descending order.

http://ffctn.com/clients/on/sfm/M17/#country/ng/o/a91af551-a806-426b-832a-01a5cf6f2456!date=2014-01-01&focus=map

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn Perfect - thanks!
