### ISSUE TITLE
Mini/Full Person Dossier - Unclear what N/A is referring to

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#29]
@sam-ffctn - Under a Person's name in their mini and full dossiers there is a bold N/A - I'm not sure what this is supposed to be reading.

![image](https://cloud.githubusercontent.com/assets/18744855/21621481/35aa0dfa-d1c7-11e6-966d-d06a96efd04d.png)

It may be left over from an old idea - if so we can just get rid of it

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor In the code I see that it was refereeing to *organization*, but in the design document it seems to have been some kind of role ex: *police*. Neither are available in the API (technically organization exists under memberships, but this is a list). 

So I'll remove it for now.

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn Great - we don't need it for now so lets just keep it out.

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor it has been removed

http://ffctn.com/clients/on/sfm/M17/#country/ng/p/352ac951-76aa-46a2-af69-b0799fb9dba3!date=2014-01-01&focus=map

both from mini dossier and dossier.
