### ISSUE TITLE
Full Dossier - Current Location, Map, Area of Operations

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#30]
@sam-ffctn - the Person's full dossier - has the same featuers of the Organization's dossier - the Current Location, Map, Headquarters, Location, and Area of Responsibility --- I think we can get rid of all of it since it isn't relevant to how we capture data on a Person currently.

![image](https://cloud.githubusercontent.com/assets/18744855/21621801/9ad9707a-d1c8-11e6-8c70-0cc7ca96f740.png)

http://ffctn.com/clients/on/sfm/M16/#country/ng/p/f0366f30-4621-4d46-bbaa-13381d2b4149!date=2014-01-01&focus=map&classifications=Army&overlay=person-dossier

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor the fields have been removed

http://ffctn.com/clients/on/sfm/M17/#country/ng/p/352ac951-76aa-46a2-af69-b0799fb9dba3!date=2014-01-01&focus=map&overlay=person-dossier
