### ISSUE TITLE
Map - Not displaying Installations

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#31]
@sam-ffctn -  the map isn't displaying any Installations - this may be relatd to #26

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @evz The installations doesn't seem to be implemented at all. I'm not quite sure where to get the data for these installations? Is is in `GET /coutries/:id/map` under `organizations>properties>site_current>location`? This value also seems to be under `organization>geometry`.

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn @evz Installations should be the Site(s) for the Organization.

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor ok the sites/installations are now added to the map and can be hidden using the legend. 

Hovering over an installation will highlight the corresponding organization area (most sites don't have organizations with defined areas).

Clicking on an organization will bring up its organization mini dossier.

http://ffctn.com/clients/on/sfm/M18/#country/ng!date=2014-01-01&focus=map

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn This is working well - can we have the tooltip appear when a user hovers over an installation?

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn - installations aren't showing again --- http://ffctn.com/clients/on/sfm/M18/#country/ng!date=2014-01-01&focus=map

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @evz this seems to be an api bug, the `location` property is always returning `null` now instead of the expected point data. 

The API end point in question: https://sfm.datamade.us/api/countries/ng/map/?tolerance=0.01&at=2014-01-01

**Comment by tonysecurityforcemonitor** [comment]
I suspect this is related to #26

**Comment by evz** [comment]
OK, I figured this out. At some point I removed the code that updated the coordinates for the sites as they were being imported from the Google Sheet. D'oh. It's back and I am running an import / refresh to get that `location` property populated.

**Comment by evz** [comment]
That property should be populated now. Sorry about that.

**Comment by tonysecurityforcemonitor** [comment]
This is working now - I'll pull the tooltip comment into a new/clean issue.
