### ISSUE TITLE
Map - Overlapping Areas of Operation

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#32]
@sam-ffctn - can we implement something so that if a user hovers over an Area of Operation for a number of seconds the tooltip/selection will move from the top layer to the layer below?

Right now the smallest Area of Operation is the top layer which is good - however there will be Organizations whose Area of Operation will be completely covered by smaller Areas of Operation for other organizations

**Comment by jsmoak** [comment]
@tonysecurityforcemonitor Currently there is a parallel structure set up in the map to view the Areas of Operation for organizations, in case the situation you mentioned occurs.

**Comment by tonysecurityforcemonitor** [comment]
@jsmoak Sorry - can you explain a bit more about the parallel structure?

**Comment by jsmoak** [comment]
@tonysecurityforcemonitor Sure - When in the Area of Operations map, if for any reason you can not see the organization on the tooltip (should only be in the instance where the smaller ones are hiding the larger), the user can click on the organization on the right-hand panel, and access it that way.

**Comment by tonysecurityforcemonitor** [comment]
@jsmoak - just because we have so many organizations in the Monitor and the right hand panel is static it would be great if a user could see underneath via hovering --- however, if this would require significant time to implement let's table it. Users can also use the search function too.

**Comment by tonysecurityforcemonitor** [comment]
Tabled re: call
