### ISSUE TITLE
Export Features

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#34]
@sam-ffctn - I don't think we have everything in order to implement the Export CSV or Export Text functionalities currently listed on various pages.

![image](https://cloud.githubusercontent.com/assets/18744855/22220579/39759fba-e17d-11e6-9313-630bdea43f79.png)

Can we just change to Export Data (coming soon!) - or remove that section all together?

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor I removed this section from the search, the dossiers and the country profile.

ex: http://ffctn.com/clients/on/sfm/M19/#country/ng/o/acc51404-b07c-430b-895a-88c4c63d305e!date=2014-01-01&focus=country&perspective=organizations

**Comment by tonysecurityforcemonitor** [comment]
Great thanks!
