### ISSUE TITLE
Dossier - renaming Headquarters to Installations

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#35]
@sam-ffctn - Can we rename the section that is currently titled "Headquarters" to "Installations"? It will be nice to standardize terminology from the Map Legend across other functionalities.

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor this is updated in the latest version: http://ffctn.com/clients/on/sfm/M20/
Changed in both the dossier and mini dossier.

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn Perfect -thanks!
