### ISSUE TITLE
Dossier - Sources not displaying?

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#36]
@sam-ffctn - The sources in the dossier aren't displaying any more - we had implemented a fix so that anything in the dossier that had sources was being displayed but currently only the sources for the Organization's name seem to be displaying.

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn - To clarify I mean both sources and confidence scores for each section of the dossier. We should keep all the sources together in one section (ala Wikipedia) as it is currently implemented.

@evz This may be an API issue...

Sources are currently displaying for: 

1. Name
2. Other Names


Sources should be also displaying for:

1. Classification
2. Commander
3. Former Commanders
4. Area of Operations
5. Headquarters (Site)
6. Superior Organizations
7. Subordinate Organizations
8. Affiliated Persons
9. Other Affiliations

**Comment by sam-ffctn** [comment]
@evz @tonysecurityforcemonitor 

Here is the current status for all the field sources:

Classification
- This seems to be working properly

Commander 
- source only listed under `people` instead of under `commander_present`
- unconventional formatting for confidence using ie. "1" instead of "low".

Former Commanders
- source only listed under `people` instead of under `commanders_former`
- unconventional formatting for confidence using ie. "1" instead of "low".

Area of Operations
- No `source` or `confidence` property in `areas.properties`

Headquarters (Site)
- No `source` or `confidence` property in `sites.properties`

Superior Organizations
- This should now be displaying its sources (this was a front-end issue)

Subordinate Organizations
- This should now be displaying its sources (this was a front-end issue)

Affiliated Persons
- unconventional formatting for confidence using ie. "1" instead of "low".

Other Affiliations
- Missing `confidence` property in `memberships`

When the API is update all the sources should be displaying correctly.

**Comment by tonysecurityforcemonitor** [comment]
> Classification - This seems to be working properly

I can't get it to display - example: http://ffctn.com/clients/on/sfm/M20/#country/ng/o/891f25a2-2eed-4765-af76-130dcee6358c!date=2014-01-01&focus=map&overlay=organization-dossier

![image](https://cloud.githubusercontent.com/assets/18744855/22894344/b2b39cd2-f1e6-11e6-8f0d-4f67f68dd3bb.png)

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @evz that organization doesn't have any sources listed in the API call.  

this one does however: http://ffctn.com/clients/on/sfm/M20/#country/ng/o/6233bb7a-410b-46ce-a9dd-30ac11afc2c5!date=2014-01-01&focus=chart

If that organization is supposed to have sources then it would be a bug with the API

**Comment by tonysecurityforcemonitor** [comment]
Ah ok thanks @sam-ffctn that's helpful. @evz there should be sources for that classification... I see them in the Master Import list.

**Comment by tonysecurityforcemonitor** [comment]
@evz this also raises a question about security-force-monitor/sfm-cms#104 - was this an issue in the API or did the sources not make it into the CMS?

**Comment by evz** [comment]
@tonysecurityforcemonitor I'm pretty sure this is fixed now.

**Comment by tonysecurityforcemonitor** [comment]
Most of this is fixed @evz but there are a few outstanding issues - I've copied from Sam's note above the sections that still need work:

Affiliated Persons

unconventional formatting for confidence using ie. "1" instead of "low".

Area of Operations

No source or confidence property in areas.properties

Headquarters (Site)

No source or confidence property in sites.properties

Other Affiliations

Missing confidence property in memberships

**Comment by tonysecurityforcemonitor** [comment]
Hi @evz just checked the newest version and this is still an outstanding issue - see the comment above for the list of issues.

**Comment by evz** [comment]
@tonysecurityforcemonitor I just deployed some changes that should address these last few things.

**Comment by tonysecurityforcemonitor** [comment]
@evz - great the only outstanding issues here are:

Area of Operations

No source or confidence property in areas.properties

Headquarters (Site)

No source or confidence property in sites.properties

This might be tied to #54

**Comment by evz** [comment]
@sam-ffctn I hate to punt this but I added the properties that @tonysecurityforcemonitor mentions above to the API response. Is there some modifications to the client side that need to happen to get those to display?

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @evz yup I had to update the frontend, should work now.

ex: http://ffctn.com/clients/on/sfm/M23/#country/ng/o/14d9a9a9-95bc-40e9-ac90-7bd3f06c81cf!date=2014-01-01&focus=map&overlay=organization-dossier

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn @evz - there is an issue with the Area - right now it is only displaying one confidence score and one source - whereas there are different sources for each Area and different confidence scores - http://ffctn.com/clients/on/sfm/M23/#country/ng/o/4a4045b6-4bcb-441a-832a-498085bd2516!date=2014-01-01&focus=map&classifications=Army&overlay=organization-dossier

@evz - I think this might be because of how the API handles Area, is there a way to seperate them out so that the dates, confidence scores and sources attach to the right areas?

**Comment by tonysecurityforcemonitor** [comment]
Sorry @evz I didn't include enough context in my comment above - I was referring to our discussion: 

> collection of all the shapes (or points) that preserves the boundaries between the shapes and is much faster because it's just a simpler operation.

**Comment by evz** [comment]
@tonysecurityforcemonitor I can certainly provide the data in a way that makes those pieces of information distinct. I think we'd need to talk through what that might look like with @sam-ffctn so that it's usable for him.

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @evz It would be better to keep the areas separate (as it was before) for the **/organizations/:id** requests (we need to keep areas aggregated for the map requests). 

I don't believe I use the `geometry` property anywhere for the **/organizations/:id** requests if that helps.

I think `sites` still behaves like this (doesn't aggregate them).

Once that is done the areas should render properly

**Comment by evz** [comment]
```
drwxrwxr-x  6 datamade www-data 4.0K Mar 13 18:25 civic-json-worker
drwxr-xr-x 11 datamade www-data 4.0K Feb  9 20:25 college-matching
drwxr-xr-x  2 datamade www-data 4.0K Mar  9 17:23 college-matching-django
drwxr-xr-x  9 datamade www-data 4.0K Mar  9 17:23 college-matching-staging
drwxrwxr-x 23 datamade www-data 4.0K Feb 10  2016 depaul_ihs
drwxrwxr-x 23 datamade www-data 4.0K Jun  6  2016 depaul_ihs_stage
drwxr-xr-x  7 datamade www-data 4.0K Feb 28 19:16 election-transcriber
drwxrwxr-x  6 datamade www-data 4.0K Aug 30  2016 election-transcriber-staging
drwxrwxr-x  6 datamade www-data 4.0K Apr 15  2016 iseif-dashboard
drwxrwxr-x  7 datamade www-data 4.0K Feb 10  2016 media
drwxr-xr-x  8 datamade www-data 4.0K Mar 10 21:45 neighborhood-fund
drwxr-xr-x  2 datamade www-data 4.0K Mar 10 21:45 neighborhood-fund-deploy
drwxr-xr-x  8 datamade www-data 4.0K Mar  2 19:49 neighborhood-fund-staging
drwxr-xr-x  6 datamade www-data 4.0K Feb 10 19:55 parserator-api
drwxr-xr-x  4 datamade www-data 4.0K Jan 26 22:17 property-image-cache
drwxrwxr-x  7 datamade www-data 4.0K Feb 10  2016 staging_media
drwxr-xr-x 10 datamade www-data 4.0K Mar  8 09:13 thrive-zones-django
drwxr-xr-x  2 datamade www-data 4.0K Mar  8 09:13 thrive-zones-django-deploy
drwxr-xr-x 10 datamade www-data 4.0K Mar  7 23:00 thrive-zones-django-staging
```

plus static sites:

```
drwxr-xr-x  3 root   root   4.0K Jan 10 21:34 another-test-hooks
drwxr-xr-x 13 ubuntu ubuntu 4.0K Mar 10 20:52 chihacknight.org
drwxr-xr-x  5 ubuntu ubuntu 4.0K Feb 24 21:58 CUAMP
drwxr-xr-x 17 ubuntu ubuntu 4.0K Mar 10 21:11 datamade.us
drwxr-xr-x 10 ubuntu ubuntu 4.0K Feb 20 22:17 dedupe.io
drwxr-xr-x  7 ubuntu ubuntu 4.0K Nov 11 21:35 generation-all-viz
drwxr-xr-x  9 ubuntu ubuntu 4.0K Feb 14 20:34 ihs-charts
drwxr-xr-x  7 root   root   4.0K Apr  8  2016 ihs-housing-stock
drwxr-xr-x  8 root   root   4.0K Oct 13 01:12 ihs-price-index
drwxr-xr-x  8 root   root   4.0K Oct 11 22:19 ihs-price-index-dev
drwxr-xr-x  9 ubuntu ubuntu 4.0K Nov 17 17:58 justice-audit
drwxr-xr-x  6 ubuntu ubuntu 4.0K Jan 27 04:35 million-dollar-blocks
drwxr-xr-x  7 ubuntu ubuntu 4.0K Nov 21 04:03 my-reps
drwxr-xr-x  7 ubuntu ubuntu 4.0K Jul 25  2016 my-reps-pbp
drwxr-xr-x  9 root   root   4.0K Feb 23 21:04 ny-budget
drwxr-xr-x 10 ubuntu ubuntu 4.0K Feb 10 17:00 probation-resources-map
drwxr-xr-x 11 ubuntu ubuntu 4.0K Feb 13 17:50 second-city-zoning
drwxr-xr-x  3 root   root   4.0K Jan 10 21:25 test-hooks
drwxrwxr-x  8 ubuntu ubuntu 4.0K Jan 10 20:43 thrive-zones
```

**Comment by evz** [comment]
Woops, sorry about the earlier comment. Totally pasted that in the wrong thread!

**Comment by sam-ffctn** [comment]
@evz I'm not sure what earlier comment you are talking about? Is it possible to structure it as I mentioned above?

**Comment by evz** [comment]
Yeah, it is. 

The earlier comment I was talking about I deleted. It was something that I intended to past into a comment box on a completely different project and accidentally pasted here. You may have gotten an email notification about about it. If so, you can disregard it.

**Comment by evz** [comment]
This fix should be deployed. Let me know if it's doing what you expect.

**Comment by tonysecurityforcemonitor** [comment]
@evz the Areas are now displaying with their respective sources and confidence scores --- but now the dates aren't displaying...

**Comment by tonysecurityforcemonitor** [comment]
@evz - Sites as well don't have their dates attached...

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @evz the date values changed names for some reason. `date_first_cited` became `date_first_cited_value`, etc. 
I updated the front-end to reflect these new names.

http://ffctn.com/clients/on/sfm/M25/#country/ng/o/06d12698-f3d1-4b61-81bc-e657b9c5eae4!date=2014-01-01&focus=map

It's not very reassuring that the api will just change property names, it can cause unexpected behavior on the front-end.

**Comment by evz** [comment]
@sam-ffctn Oh shoot! Sorry about that. I must have overlooked that when I added the sources. I could change them back if you'd like.

**Comment by sam-ffctn** [comment]
@evz ya probably best to do that. I'll undo my changes so they match up.

**Comment by evz** [comment]
OK, I changed the date fields in the `areas` and `sites` properties to be `date_first_cited` and `date_last_cited`

**Comment by sam-ffctn** [comment]
@evz @tonysecurityforcemonitor thanks it's working now

http://ffctn.com/clients/on/sfm/M25/#country/ng/o/4df27923-6644-4cdb-ad56-c31336eb614e!date=2014-01-01&focus=map&overlay=organization-dossier

**Comment by tonysecurityforcemonitor** [comment]
Looks great!
