### ISSUE TITLE
Map - Tooltip for Installations?

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#37]
@sam-ffctn Can we have a tooltip appear when a user hovers over an installation?

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn - this would be the exact same tooltip as appears when a user hovers over an Area.

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor I added the tooltip, I also added a "selected" effect to the installations.

This means that when you hover over an area you will be able to visually identify what installations are related to the organization and vice-versa.

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn Looks/works great - thanks!
