### ISSUE TITLE
Map - Installations not Filtering

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#38]
@sam-ffctn - The filter function works well for the Area of Operations on the Map, but it doesn't seem to effect the installations. I'd expect selecting Army from the Filter drop down would mean I would only see Areas of Operations and/or Installations of Organizations with a classification of Army.

**Comment by sam-ffctn** [comment]
Installations should now filter the same way that the areas filter.

ex: http://ffctn.com/clients/on/sfm/M20/#country/ng!date=2014-01-01&focus=map&classifications=Joint%20Task%20Force

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn Perfect!
