### ISSUE TITLE
Dossier - Displaying dates for Superior and Subordinate Organizations?

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#39]
@sam-ffctn - Can we display the dates for the superior and subordinate organizations in the mini and full dossiers? That extra context would be quite helpful.

**Comment by sam-ffctn** [comment]
@evz @tonysecurityforcemonitor I'm missning the `date_first_cited` and `date_last_cited` properties on the  parent and child elements for the organization endpoint.

ex: https://sfm.datamade.us/api/organizations/eda35997-21d0-4d53-a923-e9984c76afd0/

These are in the api documentation: https://github.com/security-force-monitor/sfm-proxy/blob/master/docs/organizations.md

**Comment by tonysecurityforcemonitor** [comment]
@evz @sam-ffctn - in theory the date_first_cited and date_last_cited would only apply to the "immediate" parent/child organizations - would that cut down the list of organizations displayed in the dossier? For instance this organization [(link](http://ffctn.com/clients/on/sfm/M20/#country/ng/o/9a95a773-5272-45ce-a950-e9063194b8bf!date=2014-01-01&focus=map&overlay=organization-dossier)) has quite a few organizations listed, like the 195 Battalion, which are not direct children, but rather "grandchildren" (child of a child) or "great grandchildren". Or put another way - would this mean switching from "who are all the descendants of this organization?" to "who is a child of this organization?"

It's fine if it does (and doesn't complicate anything else, like the Chart), but if it's going to cause issues then we might scrap...

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor displaying the grandchildren shouldn't have any impact on the dates being displayed.

I'm not exactly sure if we want to only show the direct children/parents of an organization. If we do, we should open up this in another issue, it shouldn't be too difficult to solve.

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn - I thinking only showing direct children/parents in the dossier would make the dates a bit clearer in my mind so let's do that - I'll create a separate issue for that.

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn Thanks for the fix on only showing direct children/parents - now the only thing remaining on this issue is displaying the ```date_first_cited``` and ```date_last_cited``` for parent/children

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @evz I'm waiting for the API include those values, as I mentioned above.

> @evz @tonysecurityforcemonitor I'm missning the date_first_cited and date_last_cited properties on the parent and child elements for the organization endpoint.
ex: https://sfm.datamade.us/api/organizations/eda35997-21d0-4d53-a923-e9984c76afd0/
These are in the api documentation: https://github.com/security-force-monitor/sfm-proxy/blob/master/docs/organizations.md

**Comment by evz** [comment]
OK, `date_first_cited` and `date_last_cited` should be available for parents and children

**Comment by tonysecurityforcemonitor** [comment]
Yep this is working
