### ISSUE TITLE
Map - Rename Legend Options

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#4]
Rename Jurisdictions as Area of Operations

**Comment by sam-ffctn** [comment]
Updated in the Organization dossier and mini-dossier

http://ffctn.com/clients/on/sfm/M13/#country/ng/o/03e9b83d-ddeb-491d-baaf-c09a49f1f64d!date=2014-01-01&focus=map

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn Wonderful!
