### ISSUE TITLE
Dossier - Area of Operation repeated multiple times?

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#41]
@sam-ffctn - sometimes the Area of Operation for an Organization is repeated multiple times - I can't find a reason in the CMS why this would be the case - @evz not sure if this is something from the API?

For example: the 1 Mechanised Division - http://ffctn.com/clients/on/sfm/M19/#country/ng/o/e7d0a9ac-708c-495d-b5da-5ce1a9fe08ee!date=2014-01-01&focus=map&classifications=Army&overlay=organization-dossier

**Comment by evz** [comment]
Huh, looks like a problem with the API. I'll look into it.

**Comment by evz** [comment]
OK. Looks like I fixed it. Sorry about that.

**Comment by tonysecurityforcemonitor** [comment]
Yep working now - thanks!
