### ISSUE TITLE
How should we flatten lists of things for CSV serialization?

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-ui#44]
The three API endpoints that, according to the spec, should optionally return a CSV version, are: 

- [ ] `/organizations/:id`
- [ ] `/people/:id`
- [ ] `/countries/:id/search/organizations`
- [ ] `/countries/:id/search/people`
- [ ] `/countries/:id/search/events`

(If there are more, let's identify them below)

As mentioned in the call, these responses return nested lists of things (so an organization will have many aliases, areas, sites, etc) and it's not obvious how we should serialize that into a tabular format. It seems like there are a few different approaches to this: 

* **Come up with some kind of delimiter** When we stick the list of values into one column in the CSV, we could just put a semicolon (";") or a pipe ("|") or something in between each of the values and it'd be up to the person who downloads the CSV to unpack that. This might work for things like lists of roles and ranks for people but it'd be a bit clunky for something more complicated like lists of sources.
* **Create a new row in the output for each variant** This is probably the cleanest and easiest thing to do (since ultimately that's kinda how the database works) but it's not super user friendly.
* **Create multiple CSV files** Instead of packing all of the data into a single file, we could create a relational database of sorts and, when a user downloads a CSV of the dossier for an organization, what they'd get is one main file that has all of the simple attributes in it and then several other files that had things like sources for the different attributes and lists of more complex things. This also seems pretty easy to implement but might not be super easy for users to unravel.
* **Some combination of the above** Sticking former commanders of an organization in a separate CSV might be sane but sticking the `other_names` for each of those in a separate file seems slightly insane. What might make more sense is to use a delimiter for each of the other names.

Any other ideas as to how we might tackle this? @tonysecurityforcemonitor Do you have any use cases in mind that might inform this?

**Comment by tonysecurityforcemonitor** [comment]
> Create a new row in the output for each variant This is probably the cleanest and easiest thing to do (since ultimately that's kinda how the database works) but it's not super user friendly.

At this initial stage I think going this route makes the most sense. Would adding a unique id for every Person, Organization and Event help make the csv more digestible? In general I'm assuming a user that downloads the Monitor's data is fairly well versed in navigating csv files and making sense of complex data. (That being said I think there are issues around properly pulling the data apart that are a bit hairy - but probably not on the csv format to resolve)

As far as an example I think the ability to download the entire dataset from: http://www.landmatrix.org/en/get-the-detail/ is generally what we're looking for

In terms of the categories - can I ask a dumb questions:

1. what is the difference between "/organizations/:id" and "/countries/:id/search/organizations" for instance?
2. Based on the first answer, should we have "/events/:id" rather than "/countries/:id/search/events"?

@tlongers how does all this strike you?

**Comment by evz** [comment]
@tlongers Do you have any additional input here? If not, I'll go ahead and start implementing the version that @tonysecurityforcemonitor suggested

**Comment by tlongers** [comment]
I'm for an open, download it all approach. However, I think the form needs more thought. If we take the current spreadsheet form as a baseline, I would not expect anyone to be able to use it successfully - the density of the model, normalisation issues, make it incomprehensible. I would focus work on an initial export function on getting out the data that answers a user's question.

**Comment by evz** [comment]
So, yeah, I guess the question depends on the context where the download is happening. I remember there being a few places where there was a "export as CSV" button but now I can't find those anymore. Do we want just one big download? Or many smaller downloads?

**Comment by tlongers** [comment]
There's a few places where CSV export is offered ([1](http://ffctn.com/clients/on/sfm/M18/#country/ng/o/9c7c5c1e-f5d7-40db-8c7c-6242ff576bb1!date=2014-01-01&focus=map&overlay=search), [2](http://ffctn.com/clients/on/sfm/M18/#country/ng!date=2014-01-01) and [3](http://ffctn.com/clients/on/sfm/M18/#country/ng/o/478f4848-eca2-41fd-93b2-d27bc81da7b6!date=2014-01-01&focus=map&overlay=organization-dossier))  As we don't really know how users want to take data home yet, perhaps include a very basic "download CSV" as a option in search results (where there's already a button)? @tonysecurityforcemonitor thoughts?

**Comment by tonysecurityforcemonitor** [comment]
@evz @tlongers I'm not sure the current workflow in the app would work well for the "getting out the data that answers a user's question" (pin here for future thinking on this). In theory the user would be downloading all the data related to an organization/person or event but without context (ie give me all the data on the 21 Brigade, as part of that data I see the parent unit is the 3 Division, but I have no other data on the 3 Division). Also do we still run into normalization issues even with a smaller download?

**Comment by evz** [comment]
@tonysecurityforcemonitor @tlongers I'm not sure where we are at with this and whether or not this is something we want to have ready for the launch coming up. I'm not sure how versed either of you are in SQL but if you check out the files in [this folder](https://github.com/security-force-monitor/sfm-cms/tree/master/sfm_pc/management/commands/sql), you can get an idea of how the extremely normalized tables that are used by the CMS are flattened out for use by the API already. The only tricky thing is that I'm putting the information about sources for each of the attributes into a JSON field which makes it easy to just attach to responses for the API (but harder to flatten out into a CSV). It would be trivial to offer the raw data (without sources) for download as CSV right now. It seems like the way to add source information is probably similar to the way it's done in the Google spreadsheet right now. Maybe we could also just create a "sources" file that comes along with the download that has IDs for each of the source rows which get referenced inside the other files that you'd download. So, something like:

```
     name      | name_source | alias | alias_source
---------------+-------------+-------+-------------
Henry Smith    | 1           | Hank  | 1
---------------+-------------+-------+-------------
Henry Smith    | 2           | Big H | 2
---------------+-------------+-------+-------------
```

And then the source table would look like

```
id |            title           | publication |    date    |             URL
---+----------------------------+-------------+------------+-------------------------------
1  | A really important article | News Daily  | 01/01/2001 | http://newsdaily.com/story-1/
---+----------------------------+-------------+------------+-------------------------------
2  | Another important story    | News Daily  | 02/10/2010 | http://newsdaily.com/story-1/
---+----------------------------+-------------+------------+-------------------------------
```

Does that make sense?

**Comment by tlongers** [comment]
Thanks for reinvigorating this thread @evz 

To get some data _into_ the CMS import format, I've been using sqlite's ```GROUP_CONCAT``` to bung multiple source citations into single cell.  But a separate table is more legible in the context of a download. Is ```oons.source_id``` unique ID or would each download have a set of indexes created specific to that download?  

Generally, though, I suggest icing work on a download function for now. My reasoning:
 * we don't know enough about what users want yet; would rather get a better view before committing time
 * I suspect someone capable of reconstructing data from a set of CSVs could grab what they need from the API (if we choose to expose it publicly)

@tonysecurityforcemonitor ?

**Comment by tonysecurityforcemonitor** [comment]
Yes let's ice it for now - it's more important to get the platform ready for launch than to commit time to this.

I think this is a really good question for @tlongers and I to farm out to particular users post launch. I suspect the number of users that do want to play around with csvs is quite small, but also quite expert, so it would be good to spend a bit of time in dialogue with them.

**Comment by evz** [comment]
@tlongers Yeah, those `source_id` columns are unique for the source table so it would be possible right now to have a single "sources" file that would relate to whatever else was downloaded.

I mean, the API _is technically_ public right now. It's just undocumented and somewhat specific to the use case of powering that particular UI. 

I'm OK with icing this and I like the idea of getting user feedback. I just wanted to make sure I wasn't skipping anything.

**Comment by tlongers** [comment]
Ok - closing for now.
