### ISSUE TITLE
Person Dossiers no longer loading

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#46]
@evz has there been an API change that could have caused this? For example every person related to http://ffctn.com/clients/on/sfm/M20/#country/ng/o/358c956b-29ca-4dc4-b1ff-847d040d0fbc!date=2014-01-01&focus=map&classifications=Army&overlay=organization-dossier  - now no longer has their job history display. The only data that seems to be loading is alternative names.

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @evz The only properties I'm displaying from the person are
`memberships`, `events` and `other_names`.

The requests I'm getting back seem to always have the `memberships` and `events` properties empty.

ex: https://sfm.datamade.us/api/people/965a000c-049b-4d9c-974f-9cca4e868286/

**Comment by tonysecurityforcemonitor** [comment]
@evz Can you take a look at this?

**Comment by evz** [comment]
@tonysecurityforcemonitor I figured out why `memberships` is always blank (fix incoming) but the reason why `events` is always blank is because it's always blank in the spreadsheet. The "Perpetrator Name" column is always blank.

**Comment by evz** [comment]
(By the way, I just deployed the fix for the `memberships` property)

**Comment by tonysecurityforcemonitor** [comment]
Great thanks @evz ! I'll tackle Events in a separate Issue
