### ISSUE TITLE
Dossiers - Only Display Direct Child/Parents

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#47]
@sam-ffctn - creating an issue as discussed in #39

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor only immediate relatives should now show in the dossier and mini dossier

ex: http://ffctn.com/clients/on/sfm/M21/#country/ng/o/358c956b-29ca-4dc4-b1ff-847d040d0fbc!date=2014-01-01&focus=chart

**Comment by tonysecurityforcemonitor** [comment]
Great!
