### ISSUE TITLE
Create Summary text for Mexico and peacekeeping countries

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#48]
To do for Tony

**Comment by jsmoak** [comment]
@tonysecurityforcemonitor hi Tony, do you have an ETA on the summary text?  We would like to go ahead and get that integrated this week.

**Comment by tonysecurityforcemonitor** [comment]
Thanks for checking in @jsmoak and perfect timing, I've just done a first draft of Mexico. I'll have everything ready to go by Friday.
