### ISSUE TITLE
Events - displaying Alleged Perpetrator Classification

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#49]
So I somehow missed this - but is it possible to add the Alleged Perpetrator Classification field for Events?

@evz this is Column N in the Events tab in the Import Master Sheet.

@sam-ffctn - I was thinking that it could look like this:

I realize this is very late in the game to raise this - so if it throws off work on other Issues let's table it.

![image](https://cloud.githubusercontent.com/assets/18744855/23216688/d8705668-f8e4-11e6-9929-c31158e8b450.png)

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @evz this isn't too difficult of a change for me, the only potential issue is that the `perpetrator_organization.classification` is a string and not an array.

ex: https://sfm.datamade.us/api/events/8a4e1795-69a2-45d6-9e38-76a449d1f295/

I can implement it either way

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn Great! @evz not sure about the string versus array issue I'll leave that to you and Sam

**Comment by evz** [comment]
OK, this should be ready to go: https://sfm.datamade.us/api/events/be961486-8ed7-4de7-b3db-8972b8384f51/

As an aside, I'm also aggregating the "other_names" for the perpetrator organizations into a list (which was formerly called "alias" and just showed one)

**Comment by tonysecurityforcemonitor** [comment]
> As an aside, I'm also aggregating the "other_names" for the perpetrator organizations into a list (which was formerly called "alias" and just showed one)

@evz Sorry -question here - how is this going to be used?

**Comment by evz** [comment]
Oh, uh, maybe it's not? I guess it just comes for free and I mentioned that because it changed.

**Comment by tonysecurityforcemonitor** [comment]
@evz ok - thanks!

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor I added the field as you requested.

ex: http://ffctn.com/clients/on/sfm/M22/#country/ng/e/8a4e1795-69a2-45d6-9e38-76a449d1f295!date=2014-01-01&focus=map

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn This is great! Quick clarification question on the nearby organizations (2km) - is that based on the Organization's Site or Area - or are both including in making that calculation? And how does time enter into that calculation - is it the Site and/or Area as of the date(s) of the event - or is there a range before/after the event?

Sorry I know we discussed this a bit back, but I can't seem to find that dicussion...

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @evz that question is for Eric, I only get the list provided by the API and I display that, I don't do any of the calculations.

ex: For this event endpoint https://sfm.datamade.us/api/events/8a4e1795-69a2-45d6-9e38-76a449d1f295/
the nearby organizations are under `organizations_nearby`

**Comment by evz** [comment]
@tonysecurityforcemonitor The radius I'm using is 35km and it is from the Organization's Site. That figure came from [this discussion](https://github.com/security-force-monitor/sfm-proxy/issues/36#issuecomment-256769617). There is no time box placed on that query right now. It seems like that would make sense, though. I'll work on making that happen.

**Comment by evz** [comment]
Also let me know if you'd like me to also query within a certain radius of an organization's area.

**Comment by tonysecurityforcemonitor** [comment]
@evz ah - thanks for the link! A time box and a query withing a certain radius of an area all makes sense to have (and would be a good query for users). If it's a lot of work let's put it off (as it is it demonstrates the idea quite nicely), if it's not too much work let's do the time box of 1 month +/- the start/end dates of an event, and for the radius let's say 35km just to keep it consistent.

**Comment by evz** [comment]
One caveat to including the buffer for the area of operations is that the organizations that have areas of operation that cover the entire country will always show up in the results. I'm not sure if that's the desired behavior.

**Comment by tonysecurityforcemonitor** [comment]
@evz - ah good point... hmmm I think that's ok.

**Comment by evz** [comment]
OK, with that in mind, I just deployed a change that should include organizations that had as their Site or Area of operations a place that was within 35km and +/- 30 days of each individual event.

**Comment by tonysecurityforcemonitor** [comment]
@evz - now there seems to be an issue on the data side of things - for instance http://ffctn.com/clients/on/sfm/M23/#country/ng/e/faf60e67-9e15-46d6-b846-037d88b6f02f!date=2014-01-01&focus=map --- should have Alleged Perpetrator (Organization Classification) of Military (it's currently Unknown) --- the location should also be Jos - Plateau (it's currently N/A - Plateau)

**Comment by evz** [comment]
@tonysecurityforcemonitor That property exists in the response that is coming from the API. It is a list so @sam-ffctn might need to make a change to accommodate that on the client side.

**Comment by evz** [comment]
So, for instance, this is the response for the event you pointed out above: 

https://sfm.datamade.us/api/events/faf60e67-9e15-46d6-b846-037d88b6f02f/

**Comment by tonysecurityforcemonitor** [comment]
Let me know about this one @sam-ffctn - if we need to adjust the data so there are only Events with a clear Site (rather than just admin_1 data) let me know and I'll make changes. Would that effect anything on the calculations side of things @evz ?

**Comment by evz** [comment]
@tonysecurityforcemonitor Nope.

**Comment by tonysecurityforcemonitor** [comment]
Thanks @evz !

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @evz 

Originally I did not have the `perpetrator_classification` property in the API, I was merging the classifications of each organization. It's nice to have this property now, but I notice that we don't have any organizations tied to the event (from example above):
https://sfm.datamade.us/api/events/faf60e67-9e15-46d6-b846-037d88b6f02f/
How can we then determine that the `perpetrator_classification` is `Military` if no `perpetrator_organization` are listed.
I'm not sure if this is an API bug. 

Either way, I'm now showing the `perpetrator_classification` property.
and the location is fixed as well. The `admin_level_1` property disappeared, I'm now using `osm_name` instead.

fixed version: http://ffctn.com/clients/on/sfm/M24/#country/ng/e/faf60e67-9e15-46d6-b846-037d88b6f02f!date=2014-01-01&focus=map

**Comment by tonysecurityforcemonitor** [comment]
> How can we then determine that the perpetrator_classification is Military if no perpetrator_organization are listed.

@evz - On the data side of things we make this determination based on column N in the Master Import.  The bigger question your asking is actually a methodological one - classifications exist, in part, to give greater context to events like this (where no specific organization is identified) and connect those events to the Monitor's data on organizations. By analyzing the alleged event the perpetrators are described as "soldiers" which the Monitor understands to mean individuals that are part of an organization with a ```Military``` classification. Users can then see what ```Military``` organizations the Monitor has data on and hopefully launch new investigations to identify a specific perpetrator.

**Comment by tonysecurityforcemonitor** [comment]
@evz I just checked the link above - the classification is now displaying and the location is fixed - but I don't see the nearby organizations loading...

**Comment by evz** [comment]
I suspect the reason this is happening is related to what I talked about over here: https://github.com/security-force-monitor/sfm-ui/issues/45#issuecomment-286208206 If the last cited date is null for the area of an organization, how should it be treated?

**Comment by evz** [comment]
Also, for [that event](http://ffctn.com/clients/on/sfm/M24/#country/ng/e/faf60e67-9e15-46d6-b846-037d88b6f02f!date=2014-01-01&focus=map) what organizations would you expect to show up?

**Comment by tonysecurityforcemonitor** [comment]
> Also, for that event what organizations would you expect to show up?

@evz - I'd expect 3 Armoured Division, 3 Armoured Division Garrison, 82 Mechanised Battalion to show up since their Sites and/or Areas are within the km range for Events, the date ranges for their Sites fall within the +/- date range for Events, and they are classified as Military. I would not expect the Special Task Force to show up, even though it has a Military classification, since the date ranges for it's Site(s) and Area(s) fall outside that +/- date range. I would not expect Plateau State Police Command to show up, even though the date ranges for it's Site and/or Area are within that +/- date range, since it does not have a Military classification.

**Comment by evz** [comment]
OK, so, the logic for this query worked out like this:

1. First, check for organizations within 35km of event that have the classification "military" in their list of classifications.
2. If there is a start and end date for the sites or areas for organizations that are within that radius, check if that date range overlaps with +/- date range for the event. 
3. If there is a start date but no end date for the sites or areas for organizations within that radius and the "assume area of operations to current" property is false, check to see if the start date is somewhere between the start and end date of the event (or if it's the same date).
4. If there is a start date but no end date for the sites or areas for organizations within that radius and the "assume area of operations to current" property is true, check to see if there is an overlap between the date range of the event and the range of dates starting with the site or area start date and ending with the current date. 
5. If there is not a start date but there is an end date for the sites or areas for organizations within that radius, check to see if the end date is between the start and end date of the event (or is the same day). 

Does that seem to jive with how you're thinking about this @tonysecurityforcemonitor?

**Comment by tonysecurityforcemonitor** [comment]
@evz - I had small changes on points 3 and 5 - in bold are the tweaks as I see them - do they make sense?

3. If there is a start date but no end date for the sites or areas for organizations within that radius and the "assume area of operations to current" property is false, check to see if the start date is somewhere **between +/- 30 days from the start and/or end date of the event (or if it's the same date).**

5. If there is not a start date but there is an end date for the sites or areas for organizations within that radius, check to see if the end date is **between +/- 30 days from the start and/or end date of the event (or if it's the same date).**

**Comment by evz** [comment]
This fix should should be in place. Let me know if it's returning what you expect.

**Comment by tonysecurityforcemonitor** [comment]
@evz - great this is working as expected!
