### ISSUE TITLE
Map - Fix Date display

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#5]
We should make it easier for the user to see what date they have selected -- right now the date box does not seem prominent enough and the full numbered date does not even fit into the box (example screenshot below)

![image](https://cloud.githubusercontent.com/assets/18744855/19316775/bfa4eb44-9070-11e6-838a-aa598702a0a9.png)

**Comment by sam-ffctn** [comment]
For now I just resized the box to fit the date
http://ffctn.com/clients/on/sfm/M13/#country/ng!date=2014-01-01&focus=map
