### ISSUE TITLE
Map - Areas not displaying when filtered

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#51]
@evz - it looks like different areas are not being rendered on the map when I filter down to different organization classifications - for instance http://ffctn.com/clients/on/sfm/M21/#country/ng!date=2014-01-01&focus=map&classifications=Army - there should be a number of areas displayed for the various Divisions, Brigades and Battalions that aren't being displayed... are they being loaded through the API? I checked the CMS and the Areas look like they are there.

**Comment by evz** [comment]
Related to this: https://github.com/security-force-monitor/sfm-ui/issues/43#issuecomment-283410578

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor I think this issue should be fixed since #43 is solved

**Comment by tonysecurityforcemonitor** [comment]
Closing this as the discussion has been moved to #45
