### ISSUE TITLE
Classification not loading for Search results?

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#52]
@sam-ffctn - when conducting a search all of the results displayed have unknown classification - but we're still able to sort the organizations by their classification - for example searching for Kaduna State results in:

![image](https://cloud.githubusercontent.com/assets/18744855/23472022/75266c7e-fe79-11e6-8ce4-c43dd720c268.png)

As you can see on the right the classifications for both organizations Police and State Security Service respectively, are there.

**Comment by evz** [comment]
So, the classification here is the organization classification, right? That's typically a list. Which one should show up? Or is the idea to show all of them?

**Comment by tonysecurityforcemonitor** [comment]
@evz Yep sorry - this is the organization classification - the idea would be to show them all

**Comment by evz** [comment]
(anyways @sam-ffctn , I can add that to the search response, if it makes it easier)

**Comment by evz** [comment]
@tonysecurityforcemonitor @sam-ffctn The classifications for organizations should now be included in the search response

**Comment by tonysecurityforcemonitor** [comment]
Yep this is working
