### ISSUE TITLE
N/A under Organization Name

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#53]
@sam-ffctn - I think we removed this in a previous version - I believe it was supposed to be something that was never implemented...

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor I fixed this to what it should have been the `root_name` as it is in the mini-dossier

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn - ok thanks
