### ISSUE TITLE
MiniDossier/Full Dossier - Area not displaying properly

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#54]
@sam-ffctn @evz - The Area of Operations is not now displaying properly in the mini dossier/full dossier. Area is listed as N/A and the dates are also not correct...

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @evz this issue should now be solved, Although I noticed that some of the area of Operation dates are a bit weird.

ex: http://localhost:8001/index.paml#country/ng/o/0de5e37d-5819-475b-8810-eb482de30c38!date=2014-01-01&focus=map&overlay=organization-dossier
api endpoint: https://sfm.datamade.us/api/organizations/0de5e37d-5819-475b-8810-eb482de30c38/
first_cited is `2002-06-12, 2002-06-12, 2002-06-12`
and last_cited is `2016-03-13, 2016-03-13, 2016-03-13`

**Comment by tonysecurityforcemonitor** [comment]
Thanks @sam-ffctn - yes there seems to be something going on with the dates, confidence scores and sources. I made a comment in #36 and I think the two are interrelated. I'm going to close this issue so we just have the one thread going.
