### ISSUE TITLE
Map Filter Classifications

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#55]
@sam-ffctn - Can the Filter function on the map be made to only display the Organization Classifications which are present in that country (tied to the ```division_id```)? Right now the Nigeria Map has classifications that are only used in Mexico (Ejercito, Militar, etc.). Conversely it would be good for the Mexico Map to only have classifications that are present in Mexico (it appears to be that way now, though I'm not sure why that is true for Mexico but not Nigeria).

**Comment by tonysecurityforcemonitor** [comment]
Let me know if we can knock this out @sam-ffctn - I'm in the process of cleaning the Mexico data for a major update and it would be good to know how to handle the classifications in the Mexico data.

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @evz  this is an api issue.
For some reason these organizations:
https://sfm.datamade.us/api/organizations/26d9ad2a-bade-4ed0-8f5e-962c1ac8d439/
https://sfm.datamade.us/api/organizations/c7d32faa-dd75-4d80-92ac-b68795a56fdf/

Are listed under nigeria, but are actually in mexico:
You can find them under the Nigeria map endpoint:
https://sfm.datamade.us/api/countries/ng/map/?tolerance=0.01&at=2014-01-01

These organizations obviously have mexican classifications and that's why they appear in the filter.

if you zoom out of nigeria when it is selected to look at mexico it's pretty obvious
http://ffctn.com/clients/on/sfm/M24/#country/ng!date=2014-01-01&focus=map

**Comment by evz** [comment]
@sam-ffctn Oh, let me look into that. Thanks for pointing it out.

**Comment by tonysecurityforcemonitor** [comment]
Ah ok that's really helpful to know @sam-ffctn - makes my data cleaning much easier.

**Comment by tonysecurityforcemonitor** [comment]
Hi @evz - I was planning to do an update to the Master Import Sheet sometime soon - let me know if I should hold off while you're investigating this issue.

**Comment by evz** [comment]
I think I figured this out but I'll need to refresh things anyways so, go ahead and update and I'll just do it all at once after that.

**Comment by tonysecurityforcemonitor** [comment]
@evz - I haven't gotten as far into the data as I wanted to today, so I'm going to update Master Import tomorrow...

**Comment by evz** [comment]
OK. Let me know when you get that done and I'll re-run the import and that should resolve this issue.

**Comment by tonysecurityforcemonitor** [comment]
@evz I've updated the Master Import Sheet

**Comment by evz** [comment]
Dang, OK there's still something up with this. I re-ran the import and there are still organizations showing up with the wrong division ID. I'll dig a bit deeper ...

**Comment by tonysecurityforcemonitor** [comment]
@evz There may have been a data issue - I rechecked everything and saw there were two entries missing division IDs for their area or their Site. You might reimport everything again and see if that helps...

**Comment by evz** [comment]
Whew. OK, I think I figured it out. Amazing what a little pair of parentheses can cause ...

**Comment by tonysecurityforcemonitor** [comment]
@evz so it looks like everything is working here --- I didn't know if the wrong division_id/parentheses dragon has been slain ;)

**Comment by evz** [comment]
Yeah, if it looks like it's working through the UI, then I'd say it's slain.

**Comment by tonysecurityforcemonitor** [comment]
@evz excellent - thanks!
