### ISSUE TITLE
Very cluttered pop-up for Area of Responsibility

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-ui#56]
Pop-ups for Areas of Operation appear when the mouse is hovered over them. Most of the time, they provide useful summary information. 

However, they can become too large and cluttered where the Area of Operation is the aggregate of a large number of small geographical areas. As an extreme example, [hover the mouse over the Area of Responsibility for 44 Zona Militar at 2014-01-01](http://ffctn.com/clients/on/sfm/M23/#country/mx/o/66b70cef-14ba-4c14-9d6d-d79580f7be4e!date=2014-01-01&focus=map):

![ffctn_com_clients_on_sfm_m23__country_mx_o_66b70cef-14ba-4c14-9d6d-d79580f7be4e_date_2014-01-01_focus_map](https://cloud.githubusercontent.com/assets/2115933/23704594/9ff67f46-03fd-11e7-92b2-2765ceac5a76.png)

Not sure what an elegant fix would be here - perhaps truncate the list of locations when more than 5? So, in this case, the location information would be:

>Ayoquezco de Aldama, Candelaria Loxicha, Coatecas Altas, Constancia del Rosario, Heroica Ciudad de Ejutla de Crespo and 154 others.

**Comment by tonysecurityforcemonitor** [comment]
I like this idea @tlongers - @sam-ffctn, truncating at 7 would account for this, there are a couple examples in Mexico that will produce massive (100+) lists. This might also be related to how Areas are handled overall in #45.

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @tlongers 

I've updated the tooltip to behave as described above:

http://ffctn.com/clients/on/sfm/M24/#country/mx/o/66b70cef-14ba-4c14-9d6d-d79580f7be4e!date=2014-01-01&focus=map

**Comment by tlongers** [comment]
Great @sam-ffctn nice work. Small labelling fix needed: where there are 8 areas, and 7 are listed in full with single remainder, the wording should say "1 other" and not "1 others". See:
http://ffctn.com/clients/on/sfm/M24/#country/mx/o/4d5d6eb0-0b9a-4a97-bf26-c223fc56c4ae!date=2014-01-01&focus=map

**Comment by sam-ffctn** [comment]
@tlongers this is now fixed,

If you have 8 areas it will shown them all, if you have 9 it will show 7 + 2 others.
http://ffctn.com/clients/on/sfm/M24/#country/mx/o/4d5d6eb0-0b9a-4a97-bf26-c223fc56c4ae!date=2014-01-01&focus=map

**Comment by tlongers** [comment]
Elegant! Thanks @sam-ffctn 
Closing.
