### ISSUE TITLE
Pop-up tooltips appear over event dossiers, rather than over map canvas

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-ui#57]
If an event tooltip is displayed by hovering over its entry in the time slider, and the map location of that event is obscured by the Dossier window, the tooltip will display over the dossier. This can be seen [here](http://ffctn.com/clients/on/sfm/M24/#country/ng/o/8818873f-dd42-4380-b6aa-0f241000f38a!date=2014-01-01&focus=map) when hovering over Event 43 in the time slider:

![ffctn_com_clients_on_sfm_m24__country_ng_e_1c4ea6a3-ede7-418d-9823-1eda54978826_date_2014-01-01_focus_map](https://cloud.githubusercontent.com/assets/2115933/23787996/8570ab40-056c-11e7-8c7e-afc6735f5dc8.png)

**Comment by tonysecurityforcemonitor** [comment]
Thanks for the catch @tlongers - can you take a look @sam-ffctn?

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @tlongers I've adjusted the layering order, the tooltips will now be hidden by the dossier.
ex: http://ffctn.com/clients/on/sfm/M25/#country/ng/o/8818873f-dd42-4380-b6aa-0f241000f38a!date=2014-01-01&focus=map

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn - great thanks!
