### ISSUE TITLE
Time slider - date display dual use as date picker?

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-ui#58]
At some point there was an idea that there should be a date entry box as a complement to the time slider. 

![ffctn_com_clients_on_sfm_m24__country_ng_o_0b223735-ccb8-4fde-82ec-bb27b2b7ad25_date_2011-04-16_focus_map](https://cloud.githubusercontent.com/assets/2115933/23806953/a64cd772-05bb-11e7-91ed-a120387a48fb.png)

Is this still of interest for this cut? @tonysecurityforcemonitor

**Comment by tonysecurityforcemonitor** [comment]
@tlongers I think we'll put this on ice for right now --- but putting to users how to interact with time throughout the Monitor is a very good question.
