### ISSUE TITLE
Some praise - charts looking incredible

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-ui#59]
Small break from the issues usually discussed  on this queue -  I'd like to say that this looks tremendous. Clean, superb work @sam-ffctn @evz 

http://ffctn.com/clients/on/sfm/M25/#country/mx/o/97a29e56-7f77-4182-a6df-aed0c938e6b2!date=2014-01-01&focus=chart&perspective=organizations

![ffctn_com_clients_on_sfm_m25__country_mx_o_97a29e56-7f77-4182-a6df-aed0c938e6b2_date_2014-01-01_focus_chart_perspective_organizations](https://cloud.githubusercontent.com/assets/2115933/23915197/4bece25e-08e0-11e7-91cb-2ab72700517a.png)

**Comment by sam-ffctn** [comment]
thanks :)

**Comment by tonysecurityforcemonitor** [comment]
+1 on the praise!

**Comment by tlongers** [comment]
OK :) Closing the praise thread, but will re-activate it as needed.
