### ISSUE TITLE
Map - selection different areas of operation doesn't work

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#6]
When scrolling over large areas of operation its not possible to select the smaller areas contained within the larger area -- for example its not possible to select the smaller areas within the Special Task Force's Area of Operations.

As areas of operations will overlap frequently it should be possible for a user to hover over an area and be able to select one of the several units that operate there.

**Comment by sam-ffctn** [comment]
Right now the API is returning the areas as points (and we render them as such). I'm not sure if this is intentional or not. It does mitigate this issue tho.
http://ffctn.com/clients/on/sfm/M13/#country/ng!date=2014-01-01&focus=map

**Comment by tonysecurityforcemonitor** [comment]
Hey @evz I think this is an issue for you - seems API is returning areas as points

@sam-ffctn - the areas should be polygons, not points - so we'll need to revisit

**Comment by evz** [comment]
I'm a little confused by this. Areas are polygons and are returned as polygons in the API responses. So, for instance, 

Here is an organization detail: 
https://sfm.datamade.us/api/organizations/87ac8025-de2e-4292-971d-535d3d53e93e/

That same organization map view:
https://sfm.datamade.us/api/organizations/87ac8025-de2e-4292-971d-535d3d53e93e/map/?at=2014-01-01

And the chart view:
 https://sfm.datamade.us/api/organizations/87ac8025-de2e-4292-971d-535d3d53e93e/chart/?at=2014-01-01

All of those responses contain a `site` or `sites` or `sites_current` which are points and they also contain an `area` or `areas_current` which are polygons (or multipolygons as the case may be)

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn The API should be working on this issue...

**Comment by sam-ffctn** [comment]
I'm not using the `area_current` and I'm ordering the regions by area (smallest on top).
I think this works quite well.
Let me know if this needs improvement
http://ffctn.com/clients/on/sfm/M14/#country/ng!date=2014-01-01&focus=map

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn This seems to be working well - I think having some more data in the system will make it so can I test and confirm.
