### ISSUE TITLE
Re-run import and summary text for Sudan

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#61]
@evz - can you re-run the import? I realized I failed to update the Sudan peacekeeping mission.

@sam-ffctn - I'll send you summary text for Sudan right now as well.

**Comment by evz** [comment]
@tonysecurityforcemonitor I re-ran the import. It looks like I am missing OSM data for Sudan, though so nothing is showing up there. Ugh. I'll fix that and let you know when it's ready.

**Comment by tonysecurityforcemonitor** [comment]
@evz - if it helps I think you may only need the data related to that entry itself and the country boundary for Sudan. I don't think there is any other Sudan related geodata in any of the entries...

**Comment by evz** [comment]
OK, looks like Sudan is showing now. http://ffctn.com/clients/on/sfm/M25/#country/sd

**Comment by tonysecurityforcemonitor** [comment]
thanks @evz !
