### ISSUE TITLE
Country name not displaying with country summary

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#62]
@sam-ffctn - the countries are showing a large N/A where their names should be in the country summary section --- for instance http://ffctn.com/clients/on/sfm/M25/#country/ng!date=2014-01-01

![image](https://cloud.githubusercontent.com/assets/18744855/23963266/0f119634-0987-11e7-9f3b-5476d91bd28b.png)

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @evz the names and alleged events count are retrieved from this api endpoint:
ex nigeria: https://sfm.datamade.us/api/countries/ng/

This endpoint returns an empty object for the other countries
ex: https://sfm.datamade.us/api/countries/lr/

**Comment by evz** [comment]
@sam-ffctn I'll take a look at what's going on there

**Comment by evz** [comment]
OK, this is fixed. Sorry about that.

**Comment by tonysecurityforcemonitor** [comment]
Yep this is working well!
