### ISSUE TITLE
Nearby orgs radius inaccurate

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-ui#63]
On the event detail page it says the nearby organizations are within 2km. The query being executed by the API is for 35km. Seems like this should be squared.

![event-detail](https://cloud.githubusercontent.com/assets/551491/24001444/26dc8882-0a2c-11e7-949c-8265a33e7b6a.png)

**Comment by tonysecurityforcemonitor** [comment]
@evz - thanks for that catch

@sam-ffctn - can you change to 35 km?

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @evz I updated the label

http://ffctn.com/clients/on/sfm/M26/#country/ng/e/f98dadee-7cfc-4f43-9414-b8f09b382a25!date=2014-01-01&focus=map

**Comment by tonysecurityforcemonitor** [comment]
Thanks @sam-ffctn!
