### ISSUE TITLE
Nearby orgs on event detail all listed with unknown classification

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-ui#64]
The classifications for the nearby organizations are missing. I should probably add them into the API response.

![event-detail](https://cloud.githubusercontent.com/assets/551491/24001538/649dbf24-0a2c-11e7-8205-01febbe2152b.png)

**Comment by tonysecurityforcemonitor** [comment]
@evz yes that would be great - thanks

**Comment by evz** [comment]
@sam-ffctn I added a list of classifications to each of the nearby organizations that are returned with an event detail. https://sfm.datamade.us/api/events/ffd546f7-cbe8-4d5b-bd47-3497a52ff886/

**Comment by sam-ffctn** [comment]
@evz @tonysecurityforcemonitor its fixed

http://ffctn.com/clients/on/sfm/M26/#country/ng/e/58fc58ad-36d7-4774-b405-f746bffae9c0!date=2014-01-01&focus=map

**Comment by tonysecurityforcemonitor** [comment]
@evz - there is an issue with the event above - it should be returning only organizations with a Police classification - but I don't see any in the list - they are all Army and/or Military

**Comment by evz** [comment]
Oh, huh, I guess I took [this comment](https://github.com/security-force-monitor/sfm-ui/issues/49#issuecomment-286217220) too literally. How should I know what classification to use? Do I just use the perpetrator classification from the event table?

**Comment by tonysecurityforcemonitor** [comment]
@evz - no prob - yes use the perpetrator classification(s) from the Event sheet for each event

**Comment by evz** [comment]
@tonysecurityforcemonitor OK, that appears to be working now.

**Comment by tonysecurityforcemonitor** [comment]
Looks great!
