### ISSUE TITLE
Events - click through to organization's dossier

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#65]
@sam-ffctn @evz  - is it possible to make it so when a person or organization is named in an abuse the user can click through to that organization or person's dossier?

The only example that we can test on is this one: http://ffctn.com/clients/on/sfm/M26/#country/ng/e/f7249679-bb1e-4eaf-bba3-91c55e13c655!date=2014-01-01&focus=map

I'd like to make it so the user could click on the Joint Task Force and be taken to their dossier - the the ```Name``` of the organization should match up to what is in the ```Name``` column in the Organizations Sheet @evz

**Comment by evz** [comment]
@sam-ffctn should be able to build a link. In the response that comes back about the event, there's a property called `perpetrator_organization` that includes that organization's id. So, the link could just leverage that.

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor Organizations and people are now clickable on the event

http://ffctn.com/clients/on/sfm/M27/#country/ng/e/f7249679-bb1e-4eaf-bba3-91c55e13c655!date=2014-01-01&focus=map

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn - this works great, thanks!
