### ISSUE TITLE
Select and copy text on app is disabled

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-ui#66]
Is some CSS property blocking the selection and copying of text? I'm on Chrome  56.0.2924.87 (64-bit.

@tonysecurityforcemonitor

**Comment by tonysecurityforcemonitor** [comment]
I'm having the same issue too - is it possible to fix? @sam-ffctn

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @tlongers I re-enabled user-selection. Most text should be selectable now.
We often disable user-selection it can sometimes cause weird behavior with draggable elements such as the map and chart. In our case it seems to be working fine.

http://ffctn.com/clients/on/sfm/M27/#country/ng!date=2014-01-01

**Comment by tonysecurityforcemonitor** [comment]
thanks @sam-ffctn !
