### ISSUE TITLE
Source anchors not working

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-ui#67]
Should clicking the number of a source jump the page to the source as listed further down the page?

**Comment by tonysecurityforcemonitor** [comment]
@tlongers they should - @sam-ffctn can you take a look - this was working before I believe...

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @tlongers It's a bit tricky to get it to jump to the exact source. I set it up so that now it will jump to the top of the sources section

http://ffctn.com/clients/on/sfm/M28/#country/ng/o/bd3dc21d-6a89-4d78-9191-e7d2fddb780e!date=2017-03-24&focus=map

**Comment by tonysecurityforcemonitor** [comment]
Thanks @sam-ffctn that should work for now
