### ISSUE TITLE
Map - List Area of Operations Names

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#7]
Since we are using a stylized map base - it would be helpful to list the Area of Operations for an Organization in the pop-up on the maps. We could have that instead of the Aliases so as an example:

![image](https://cloud.githubusercontent.com/assets/18744855/19317089/d8592bd6-9071-11e6-83cf-f26c921b483e.png)

These would all be the Geoname for the organization's area operations (Area:geonames_name)

This would be incredibly helpful - I find myself unsure of what states in Nigeria are being covered by the Organizations just by looking at the map and I suspect many users will have difficulty as well.

**Comment by sam-ffctn** [comment]
We are now including the **area_name** and the **site_name** in the tooltip
http://ffctn.com/clients/on/sfm/M13/#country/ng!date=2014-01-01&focus=map

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn This is hard for me to test right now --- once we have the areas of operation displayed on the map and listed out in the dossier it will make is possible to test and comment.

As of right now it seems like most organizations are missing their Area of Operation

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor We weren't loading the Area of Operations properly in the Organization mini dossier. 
It should be fixed now.
http://ffctn.com/clients/on/sfm/M14/#country/ng/o/eba73af9-f22a-425f-832d-c8a36b7e5e50!date=2014-01-01&focus=map

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn I think this is fixed - I'll be able to better test once more data is inputted through the importer.

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn Can we only do the area_name in the tooltip? Having the area_name and the site_name makes it a little confusing. It's hard to tell what is what.

**Comment by sam-ffctn** [comment]
Yup, its updated now to only show area_name
http://ffctn.com/clients/on/sfm/M14/#country/ng!date=2014-01-01&focus=map

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn the only remaining question I have on this is for Organizations with multiple areas of operation - but I think it more of a question about the CMS for @evz .

Leaving this open for now and will create some issues in the CMS git thread that will address this among other things

**Comment by evz** [comment]
@tonysecurityforcemonitor A short answer is that the CMS makes an allowance for that. Organizations can have many areas of operation and sites.

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @evz is there anything that needs to be done on the frontend to support multiple areas of operation? Right now I'm just displaying the `area_name`

**Comment by tonysecurityforcemonitor** [comment]
created new issue to deal with tooltip issue
