### ISSUE TITLE
Affiliated persons - how are they generated?

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-ui#70]
What data do we expect to be in the Affiliated Persons section of an Organisation's mini-dossier?

Start here:

http://ffctn.com/clients/on/sfm/M27/#country/mx/o/5a9075d9-d00c-481d-9d5d-e0148fb05e6c!date=2013-04-09&focus=map

In this organisational record 7 persons are listed as affiliated with ```6 Zona Militar```, but no context is provided - organisation and location are blank. 

![ffctn_com_clients_on_sfm_m27__country_mx_o_5a9075d9-d00c-481d-9d5d-e0148fb05e6c_date_2013-04-09_focus_map](https://cloud.githubusercontent.com/assets/2115933/24121516/706fbc4e-0db0-11e7-8121-e71ad5df8e53.png)

Should this section have more information?

**Comment by tonysecurityforcemonitor** [comment]
Perhaps the most simple thing would be to display their ```Role``` and ```date_first_cited``` and ```date_last_cited``` that they had when they had ```membership``` with the ```Organization``` - is that possible to implement in the API @evz and the UI @sam-ffctn?

**Comment by tlongers** [comment]
We already list the previous commanders. What does this section add to that?

**Comment by tonysecurityforcemonitor** [comment]
@tlongers It should include anyone that had affiliation with an Organization - including ```People``` with no ```Role``` or a ```Role``` other than commander. Only examples of this are in the Nigeria data:  http://ffctn.com/clients/on/sfm/M27/#country/ng/p/ed069aa4-10a6-4ef0-b354-bce1488cf3ff!date=2014-01-01&focus=map&overlay=person-dossier  - or - http://ffctn.com/clients/on/sfm/M27/#country/ng/p/7ba3c87c-a265-4e80-9c78-81d5b4db06fd!date=2014-01-01&focus=map&overlay=person-dossier

**Comment by evz** [comment]
@tonysecurityforcemonitor I'm not exactly sure how that list is generated in the UI but I know that the detailed endpoint for an organization (which is loaded on that page) includes all of the info for each "affiliated person" (Role, date_first_cited, date_last_cited)

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @tlongers updated to include the fields mentioned above:

http://ffctn.com/clients/on/sfm/M28/#country/ng/o/280ad1e8-23e4-400a-867f-748731f3ff05/p/ed069aa4-10a6-4ef0-b354-bce1488cf3ff!date=2015-03-23&focus=chart

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn - this looks great - thanks!
