### ISSUE TITLE
Source anchors in superior organisations section

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-ui#71]
Related to #67. Start here:

http://ffctn.com/clients/on/sfm/M27/#country/mx/o/537cc6f6-bf53-45d5-9482-a4e70b25119b!date=2011-07-20&focus=map

Click on the source number ```44``` in the ```Superior Organisations``` section, which lists ```Estado Mayor de la Defensa Nacional```. Rather than do nothing, or jump to the footnote for source 44, clicking here will load the mini-dossier for ```Estado Mayor de la Defensa Nacional```. when #67 is fixed, this might not occur, but worth checking back.

**Comment by sam-ffctn** [comment]
@tlongers @tonysecurityforcemonitor This should be fixed now, clicking on the source will now do nothing (this was an event bubbling bug).

http://ffctn.com/clients/on/sfm/M28/#country/mx/o/e8555ef5-deca-4564-b43b-f415ff15081b!date=2011-07-20&focus=map

I'm working on a way to jump to the source definition (it's a bit trickier than you would expect with the current implementation).

**Comment by sam-ffctn** [comment]
@tlongers @tonysecurityforcemonitor this is fixed now that #67 is fixed.

**Comment by tonysecurityforcemonitor** [comment]
Wonderful - thank you @sam-ffctn for all of your work on the Monitor! It's quite an impressive product!
