### ISSUE TITLE
On activating search auto-focus on search box

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-ui#72]
Place cursor in input area of  ```is-search-left``` so user can get typing.

**Comment by tonysecurityforcemonitor** [comment]
@tlongers I think let's table this for now - especially in light of the other important issues you've added - since there is that seperation of Organizations, People or Events which comes about via the "click" - we can revisit how we help users narrow their searches (or if we do at all) later.

**Comment by tlongers** [comment]
It's a 2 second fix no?

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @tlongers This should work now

http://ffctn.com/clients/on/sfm/M28/#country/mx/p/6c828e5a-b7a6-4fd8-8013-6493e8cd1a3a!date=2011-07-20&focus=map&overlay=search

**Comment by tonysecurityforcemonitor** [comment]
@tlongers - is this working how you'd expect?

**Comment by tlongers** [comment]
:) nice.
