### ISSUE TITLE
Navigation to charts and maps from Person dossiers leaves user at dead end

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-ui#73]
Start here at this person dossier:

http://ffctn.com/clients/on/sfm/M27/#country/mx/p/6c828e5a-b7a6-4fd8-8013-6493e8cd1a3a!date=2011-07-20&focus=map&overlay=person-dossier

What would we expect to happen when selecting ```Map``` or ```Chart```? For Map, I would expect them to show me the Area of Operation of the Organization commanded by that person at ```2011-07-20```. For ```Chart``` I would expect to be shown a chart placing the Organization commanded by that person as at ```2011-07-20```. Neither of these things happen.

**Comment by tonysecurityforcemonitor** [comment]
@tlongers - I have a different take on the ```Map``` - which does seem to be displaying the entire ```Map``` as of ```2011-07-20```

I see the issue with the ```Chart``` however, the problem is that we don't have any information on what ```organization``` this person was commanding or affiliated with as of ```2011-07-20``` --- hmmm we don't really communicate that clearly to the user however

@sam-ffctn - however - when I select another date ```2010-01-19``` when we do have this person as a commander, the ```Chart``` doesn't reload and remains blank... http://ffctn.com/clients/on/sfm/M27/#country/mx/p/6c828e5a-b7a6-4fd8-8013-6493e8cd1a3a!date=2010-01-09&focus=chart&overlay=

**Comment by tonysecurityforcemonitor** [comment]
> @sam-ffctn - however - when I select another date 2010-01-19 when we do have this person as a commander, the Chart doesn't reload and remains blank... http://ffctn.com/clients/on/sfm/M27/#country/mx/p/6c828e5a-b7a6-4fd8-8013-6493e8cd1a3a!date=2010-01-09&focus=chart&overlay=

@evz is there a possible API issue?

**Comment by evz** [comment]
@tonysecurityforcemonitor I'm not sure if this is an API issue. As you noted, the API returns the fact that they were a commander on that date but I'm not really sure what information is used to render the chart. 

@sam-ffctn If something is missing or misbehaving, let me know.

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor  @tlongers 

> @sam-ffctn - however - when I select another date 2010-01-19 when we do have this person as a commander, the Chart doesn't reload and remains blank... http://ffctn.com/clients/on/sfm/M27/#country/mx/p/6c828e5a-b7a6-4fd8-8013-6493e8cd1a3a!date=2010-01-09&focus=chart&overlay=

This issue should now be solved, related to #79

> What would we expect to happen when selecting Map or Chart? For Map, I would expect them to show me the Area of Operation of the Organization commanded by that person at 2011-07-20. For Chart I would expect to be shown a chart placing the Organization commanded by that person as at 2011-07-20. Neither of these things happen.

related to issue #77

**Comment by tlongers** [comment]
Yep, fixed. Thanks @sam-ffctn
