### ISSUE TITLE
Ordering of job history in Person dossiers

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-ui#74]
e.g.

http://ffctn.com/clients/on/sfm/M27/#country/mx/p/6c828e5a-b7a6-4fd8-8013-6493e8cd1a3a!date=2011-07-20&focus=map&overlay=person-dossier

Should be date ordered, reverse chronological. Is something in the data preventing this occuring?

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn - can you order in reverse chronological? We ordered the commanders in the Organization's dossier chronologically so hopefully it should be a quick fix to do the reverse here.

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @tlongers Done.

http://ffctn.com/clients/on/sfm/M28/#country/mx/p/6c828e5a-b7a6-4fd8-8013-6493e8cd1a3a!date=2011-07-20&focus=map

**Comment by tonysecurityforcemonitor** [comment]
Excellent thanks @sam-ffctn !
