### ISSUE TITLE
Maximum date in chart time slider in chart needs to be current date

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-ui#75]
The time slider range isn't enough to display this date:

http://ffctn.com/clients/on/sfm/M27/#country/mx/o/44d09483-9fbe-4403-aab9-e7956cfbdffd!date=2016-12-12&focus=chart

Grabbing the slider and dragging leftwards has no effect.

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn - can you fix?

**Comment by sam-ffctn** [comment]
@tlongers @tonysecurityforcemonitor It's updated to include the current year, I also updated it so the default date is today's date.

http://ffctn.com/clients/on/sfm/M28/#country/ng!date=2017-03-21

**Comment by tonysecurityforcemonitor** [comment]
Great thanks @sam-ffctn !
