### ISSUE TITLE
Map view - Incomplete loading and clearing of organisation installations on date change

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-ui#76]
Starting here:

http://ffctn.com/clients/on/sfm/M27/#country/mx/!date=1997-01-24&focus=map

We get this, showing 4 installations/sites for 6 organisations:

![ffctn_com_clients_on_sfm_m27__country_mx__date_1997-01-24_focus_map](https://cloud.githubusercontent.com/assets/2115933/24123598/11573a36-0db8-11e7-9b88-4ee3d70dca0d.png)

In the URL change ```1997``` to ```2014``` and we get this:

![ffctn_com_clients_on_sfm_m27__country_mx__date_2014-01-24_focus_map](https://cloud.githubusercontent.com/assets/2115933/24123622/2db0033e-0db8-11e7-9046-b4c36c40a1c5.png)

At that date, I would expect installations/sites for a large number of organisations  - around 115. The organisational installation data is not refreshing automatically. A full Page Refresh and we get this, which is the view I would have expected the above to be:

![ffctn_com_clients_on_sfm_m27__country_mx__date_2014-01-24_focus_map](https://cloud.githubusercontent.com/assets/2115933/24123657/517307da-0db8-11e7-918b-d66210fa51f4.png)

Is this a bug? I think so. I tried bringing the organisational installation/site data up to date using the time slider and not altering the URL directly, but the result is the same.

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn - can you take a look at this?

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @tlongers This should now be fixed

http://ffctn.com/clients/on/sfm/M28/#country/mx!date=1997-01-01

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn - just tested this and its working well - thanks!
