### ISSUE TITLE
Empty chart view when browsing to person mini-dossier

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-ui#77]
Browsing directly here, I would expect this to show the person mini-dossier for ```Enrique Dena Salgado``` along with a chart for ```22 Zona Militar``` in which this person is noted as Commander:

http://ffctn.com/clients/on/sfm/M27/#country/mx/p/19e41830-724b-46a1-981c-f388c48df065!date=2016-05-12&focus=chart&perspective=organizations

It gives me a blank "Unknown Commander" chart. Manually selecting ```22 Zona Militar``` from the person's Job History section does not load that.

**Comment by tlongers** [comment]
Related to #68.

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn - is this an UI issue?

**Comment by sam-ffctn** [comment]
@tlongers @tonysecurityforcemonitor If a person is related to more than one organization it isn't clear which one should be shown/focused, right now it will preserve the chart in the state that is was in before the person is selected (I think this is the desired behavior). 

The second part of the issue should now be solved, clicking on the organization will load the proper chart with the node focused. 

http://ffctn.com/clients/on/sfm/M28/#country/mx/p/cf8a2b4b-c68a-4ca1-a9d1-94b18325cabc!date=2016-01-20&focus=chart&perspective=organizations

**Comment by tlongers** [comment]
@sam-ffctn  Agreed that the desired behaviour is to leave the chart in the state that the user has set it, even if that leads to a dead-end.  For future work we should look at changing the pattern that leads the user to such dead ends though. Fixing the second part of this issue helps the user out . So, accepting this fix.
