### ISSUE TITLE
Should chart retain zoom level and position when on switch between Orgs and Commanders?

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-ui#78]
Start here:

http://ffctn.com/clients/on/sfm/M27/#country/ng/o/bd69a73d-a398-48b6-9add-cb029e2e6d97!date=2014-01-01&focus=chart&perspective=commanders

Zoom the chart out, then hit ```Organizations```. Chart is returned to original zoom level. First time I noticed it, I was surprised by the behaviour.  As I had scrolled elsewhere on the chart I also lost my place, which wasn't helpful.

Oddly, I like the reverse of this behaviour - that the chart both re-zooms and re-centres on the active organisation when the chart display is switched from commander to organisation.

What's your view @tonysecurityforcemonitor ?

**Comment by tonysecurityforcemonitor** [comment]
@tlongers - I think let's explore with users - a lot rides on how they interact with the chart (and how the chart is organized, and which branch of the security forces they are looking at) so I think let's punt for now
