### ISSUE TITLE
Can't click through to Organization from Person Dossier

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#79]
@sam-ffctn - For some reason when I click on an ```organization``` on a person's dossier nothing happens - I'd expect that the organization's dossier would pop up - example: http://ffctn.com/clients/on/sfm/M27/#country/ng/o/7ba3c87c-a265-4e80-9c78-81d5b4db06fd/p/7ba3c87c-a265-4e80-9c78-81d5b4db06fd!date=2008-07-17&focus=chart - clicking on the Brigade doesn't do anything. We used to be able to click through...

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor it should work now

http://ffctn.com/clients/on/sfm/M28/#country/ng/p/7ba3c87c-a265-4e80-9c78-81d5b4db06fd!date=2008-07-17&focus=chart

**Comment by tonysecurityforcemonitor** [comment]
Excellent - thanks @sam-ffctn!
