### ISSUE TITLE
Map - Country summary

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#8]
I'm not sure where the country summary "lives" and how it will be updated --- I know this requires me to finalize a country summary for the countries of the SFM(!)

I can email text for each country that we will then address in future versions of the Monitor as far as updating it.

**Comment by sam-ffctn** [comment]
Right now it displays the value that is returned from this endpoint: https://sfm.datamade.us/api/countries/ng/
(currently it's always null)

It would also be possible to add it statically (we would just need the copy).

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn Ok - let's add statically unless that creates an issue for @evz

**Comment by evz** [comment]
That should be fine. This was something that was kinda unclear to me, too. Perhaps this could be something that could be managed through the CMS eventually.

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor is the static content ready yet? I don't think we received any copy yet.

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn Sorry still working on it!

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor  I added the country summary for Nigeria
http://ffctn.com/clients/on/sfm/M15/#country/ng/!date=2014-01-01
