### ISSUE TITLE
If organisational tree returns no information, tell the user what to do next

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-ui#80]
The below conditions return a blank canvas for the organization hierarchy chart, per #68, #73, #77 and #79:

* The user navigates directly to a chart view with a person displaying in the mini-dossier; 
* the chart does not inherit a state from previous user actions; and
* there is no data for a person or organization at a particular time.

To help the user out and leverage @sam-ffctn's fixes, place the following message in the chart: 
>No data to display - choose an organisation from this person's job history

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn - can you implement this change?

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @tlongers This should behave as described above

http://ffctn.com/clients/on/sfm/M28/#country/ng/p/0311d654-3c3a-4e23-83ae-10a28f1ce218!date=2017-03-23&focus=chart

On another note, the final issues should be done by tomorrow.

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn - thanks for the fix here - this looks good. That's great to hear about the other issues!
