### ISSUE TITLE
100% CPU use forever on Firefox

### ISSUE THREAD

**Issue by evz** [security-force-monitor/sfm-ui#82]
In the process of setting up the client parts, I noticed that my browser (Firefox) is consistently using 100% CPU for all pages on the site no matter what I'm looking at. This makes things pretty unusable at times and makes the site seem very laggy. I dug into it a bit and found that there is a CSS animation that is continuing to be animated forever whether or not it is displayed (it's the little twirly arrow thing that you get while it's loading things). As far as I can tell, there are a couple Javascript functions that toggle a `loading` class that tells the little arrow thing to either be fully opaque or fully transparent. 

@tonysecurityforcemonitor This seems to make the site somewhat unusable in Firefox. Chrome doesn't have this problem.

**Comment by tonysecurityforcemonitor** [comment]
Thanks for highlighting @evz --- there are some issues with the UI in IE as well unfortunately. We'll just have to accept this prototype is Chrome-only right now I think...

**Comment by evz** [comment]
I'm going to punt this for now. It's proving a bit more challenging than I thought it was going to be to unravel. We'll just keep this open for when we're reworking things down the road.

**Comment by tonysecurityforcemonitor** [comment]
Ok sounds good @evz - thanks for the update. We can put some language on the site about how the prototype is currently Chrome only

**Comment by tlongers** [comment]
Hmm is it something to do with `.Sidebar:before, .Dossier:before`. 

I can see it spinning infinitely in Chrome as well, through Developer Tools, which has a surreal effect:

![https___front_securityforcemonitor_org__country_mx_date_2017-04-08_focus_map_and_security_force_monitor_ _we_create_open_data_about_security_force_units_and_commanders](https://cloud.githubusercontent.com/assets/2115933/24826971/0577ef54-1c3a-11e7-9f1e-f7da42a902ae.png)

@sam-ffctn help pretty please ... :)

**Comment by evz** [comment]
Yeah, that's precisely it.

**Comment by sam-ffctn** [comment]
@evz @tlongers Thanks for diagnosing that for me, it was indeed the culprit.

fixed version: https://ffctn.com/clients/on/sfm/M29/

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor How should I push the updates to the repo? pull request? I can also provide a tarball

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn Thanks for your quick work on this! @evz what's the best way for you to get the updates?

**Comment by evz** [comment]
@sam-ffctn That sounds fine. Thanks!

**Comment by sam-ffctn** [comment]
@evz here is the tarball https://ffctn.com/clients/on/sfm/sfm-2017-04-10.tar.gz
